#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanhGiaDoanVien.Other_Class
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="danhGiaDoanVien")]
	public partial class DanhGiaDoanVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiDoan(ChiDoan instance);
    partial void UpdateChiDoan(ChiDoan instance);
    partial void DeleteChiDoan(ChiDoan instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertDoanVienUuTuGV(DoanVienUuTuGV instance);
    partial void UpdateDoanVienUuTuGV(DoanVienUuTuGV instance);
    partial void DeleteDoanVienUuTuGV(DoanVienUuTuGV instance);
    partial void InsertDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void UpdateDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void DeleteDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertKetQuaChiDoan(KetQuaChiDoan instance);
    partial void UpdateKetQuaChiDoan(KetQuaChiDoan instance);
    partial void DeleteKetQuaChiDoan(KetQuaChiDoan instance);
    partial void InsertKetQuaGiangVien(KetQuaGiangVien instance);
    partial void UpdateKetQuaGiangVien(KetQuaGiangVien instance);
    partial void DeleteKetQuaGiangVien(KetQuaGiangVien instance);
    partial void InsertKetQuaSinhVien(KetQuaSinhVien instance);
    partial void UpdateKetQuaSinhVien(KetQuaSinhVien instance);
    partial void DeleteKetQuaSinhVien(KetQuaSinhVien instance);
    partial void Insertnam(nam instance);
    partial void Updatenam(nam instance);
    partial void Deletenam(nam instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public DanhGiaDoanVienDataContext() : 
				base(global::DanhGiaDoanVien.Properties.Settings.Default.danhGiaDoanVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DanhGiaDoanVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DanhGiaDoanVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DanhGiaDoanVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DanhGiaDoanVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiDoan> ChiDoans
		{
			get
			{
				return this.GetTable<ChiDoan>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<DoanVienUuTuGV> DoanVienUuTuGVs
		{
			get
			{
				return this.GetTable<DoanVienUuTuGV>();
			}
		}
		
		public System.Data.Linq.Table<DoanVienUuTuSV> DoanVienUuTuSVs
		{
			get
			{
				return this.GetTable<DoanVienUuTuSV>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaChiDoan> KetQuaChiDoans
		{
			get
			{
				return this.GetTable<KetQuaChiDoan>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaGiangVien> KetQuaGiangViens
		{
			get
			{
				return this.GetTable<KetQuaGiangVien>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaSinhVien> KetQuaSinhViens
		{
			get
			{
				return this.GetTable<KetQuaSinhVien>();
			}
		}
		
		public System.Data.Linq.Table<nam> nams
		{
			get
			{
				return this.GetTable<nam>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiDoan")]
	public partial class ChiDoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _ten;
		
		private int _soThanhVien;
		
		private int _tongSV;
		
		private int _tongNuSV;
		
		private int _tongGV;
		
		private int _tongNuGV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnsoThanhVienChanging(int value);
    partial void OnsoThanhVienChanged();
    partial void OntongSVChanging(int value);
    partial void OntongSVChanged();
    partial void OntongNuSVChanging(int value);
    partial void OntongNuSVChanged();
    partial void OntongGVChanging(int value);
    partial void OntongGVChanged();
    partial void OntongNuGVChanging(int value);
    partial void OntongNuGVChanged();
    #endregion
		
		public ChiDoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soThanhVien", DbType="Int NOT NULL")]
		public int soThanhVien
		{
			get
			{
				return this._soThanhVien;
			}
			set
			{
				if ((this._soThanhVien != value))
				{
					this.OnsoThanhVienChanging(value);
					this.SendPropertyChanging();
					this._soThanhVien = value;
					this.SendPropertyChanged("soThanhVien");
					this.OnsoThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSV", DbType="Int NOT NULL")]
		public int tongSV
		{
			get
			{
				return this._tongSV;
			}
			set
			{
				if ((this._tongSV != value))
				{
					this.OntongSVChanging(value);
					this.SendPropertyChanging();
					this._tongSV = value;
					this.SendPropertyChanged("tongSV");
					this.OntongSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNuSV", DbType="Int NOT NULL")]
		public int tongNuSV
		{
			get
			{
				return this._tongNuSV;
			}
			set
			{
				if ((this._tongNuSV != value))
				{
					this.OntongNuSVChanging(value);
					this.SendPropertyChanging();
					this._tongNuSV = value;
					this.SendPropertyChanged("tongNuSV");
					this.OntongNuSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongGV", DbType="Int NOT NULL")]
		public int tongGV
		{
			get
			{
				return this._tongGV;
			}
			set
			{
				if ((this._tongGV != value))
				{
					this.OntongGVChanging(value);
					this.SendPropertyChanging();
					this._tongGV = value;
					this.SendPropertyChanged("tongGV");
					this.OntongGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNuGV", DbType="Int NOT NULL")]
		public int tongNuGV
		{
			get
			{
				return this._tongNuGV;
			}
			set
			{
				if ((this._tongNuGV != value))
				{
					this.OntongNuGVChanging(value);
					this.SendPropertyChanging();
					this._tongNuGV = value;
					this.SendPropertyChanged("tongNuGV");
					this.OntongNuGVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taiKhoan1;
		
		private string _matKhau;
		
		private string _MSGV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaiKhoan1Changing(string value);
    partial void OntaiKhoan1Changed();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnMSGVChanging(string value);
    partial void OnMSGVChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="taiKhoan", Storage="_taiKhoan1", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taiKhoan1
		{
			get
			{
				return this._taiKhoan1;
			}
			set
			{
				if ((this._taiKhoan1 != value))
				{
					this.OntaiKhoan1Changing(value);
					this.SendPropertyChanging();
					this._taiKhoan1 = value;
					this.SendPropertyChanged("taiKhoan1");
					this.OntaiKhoan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGV", DbType="VarChar(10)")]
		public string MSGV
		{
			get
			{
				return this._MSGV;
			}
			set
			{
				if ((this._MSGV != value))
				{
					this.OnMSGVChanging(value);
					this.SendPropertyChanging();
					this._MSGV = value;
					this.SendPropertyChanged("MSGV");
					this.OnMSGVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanVienUuTuGV")]
	public partial class DoanVienUuTuGV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _MSGV;
		
		private int _idKetQuaChiDoan;
		
		private int _phieuBau;
		
		private int _tongPhieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMSGVChanging(string value);
    partial void OnMSGVChanged();
    partial void OnidKetQuaChiDoanChanging(int value);
    partial void OnidKetQuaChiDoanChanged();
    partial void OnphieuBauChanging(int value);
    partial void OnphieuBauChanged();
    partial void OntongPhieuChanging(int value);
    partial void OntongPhieuChanged();
    #endregion
		
		public DoanVienUuTuGV()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGV", DbType="VarChar(10)")]
		public string MSGV
		{
			get
			{
				return this._MSGV;
			}
			set
			{
				if ((this._MSGV != value))
				{
					this.OnMSGVChanging(value);
					this.SendPropertyChanging();
					this._MSGV = value;
					this.SendPropertyChanged("MSGV");
					this.OnMSGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKetQuaChiDoan", DbType="Int NOT NULL")]
		public int idKetQuaChiDoan
		{
			get
			{
				return this._idKetQuaChiDoan;
			}
			set
			{
				if ((this._idKetQuaChiDoan != value))
				{
					this.OnidKetQuaChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idKetQuaChiDoan = value;
					this.SendPropertyChanged("idKetQuaChiDoan");
					this.OnidKetQuaChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phieuBau", DbType="Int NOT NULL")]
		public int phieuBau
		{
			get
			{
				return this._phieuBau;
			}
			set
			{
				if ((this._phieuBau != value))
				{
					this.OnphieuBauChanging(value);
					this.SendPropertyChanging();
					this._phieuBau = value;
					this.SendPropertyChanged("phieuBau");
					this.OnphieuBauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongPhieu", DbType="Int NOT NULL")]
		public int tongPhieu
		{
			get
			{
				return this._tongPhieu;
			}
			set
			{
				if ((this._tongPhieu != value))
				{
					this.OntongPhieuChanging(value);
					this.SendPropertyChanging();
					this._tongPhieu = value;
					this.SendPropertyChanged("tongPhieu");
					this.OntongPhieuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanVienUuTuSV")]
	public partial class DoanVienUuTuSV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _MSSV;
		
		private int _idKetQuaChiDoan;
		
		private int _phieuBau;
		
		private int _tongPhieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OnidKetQuaChiDoanChanging(int value);
    partial void OnidKetQuaChiDoanChanged();
    partial void OnphieuBauChanging(int value);
    partial void OnphieuBauChanged();
    partial void OntongPhieuChanging(int value);
    partial void OntongPhieuChanged();
    #endregion
		
		public DoanVienUuTuSV()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(10)")]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKetQuaChiDoan", DbType="Int NOT NULL")]
		public int idKetQuaChiDoan
		{
			get
			{
				return this._idKetQuaChiDoan;
			}
			set
			{
				if ((this._idKetQuaChiDoan != value))
				{
					this.OnidKetQuaChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idKetQuaChiDoan = value;
					this.SendPropertyChanged("idKetQuaChiDoan");
					this.OnidKetQuaChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phieuBau", DbType="Int NOT NULL")]
		public int phieuBau
		{
			get
			{
				return this._phieuBau;
			}
			set
			{
				if ((this._phieuBau != value))
				{
					this.OnphieuBauChanging(value);
					this.SendPropertyChanging();
					this._phieuBau = value;
					this.SendPropertyChanged("phieuBau");
					this.OnphieuBauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongPhieu", DbType="Int NOT NULL")]
		public int tongPhieu
		{
			get
			{
				return this._tongPhieu;
			}
			set
			{
				if ((this._tongPhieu != value))
				{
					this.OntongPhieuChanging(value);
					this.SendPropertyChanging();
					this._tongPhieu = value;
					this.SendPropertyChanged("tongPhieu");
					this.OntongPhieuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSGV;
		
		private string _ten;
		
		private string _gioiTinh;
		
		private string _chiDoan;
		
		private bool _doanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSGVChanging(string value);
    partial void OnMSGVChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnchiDoanChanging(string value);
    partial void OnchiDoanChanged();
    partial void OndoanVienChanging(bool value);
    partial void OndoanVienChanged();
    #endregion
		
		public GiangVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSGV
		{
			get
			{
				return this._MSGV;
			}
			set
			{
				if ((this._MSGV != value))
				{
					this.OnMSGVChanging(value);
					this.SendPropertyChanging();
					this._MSGV = value;
					this.SendPropertyChanged("MSGV");
					this.OnMSGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiDoan", DbType="VarChar(10)")]
		public string chiDoan
		{
			get
			{
				return this._chiDoan;
			}
			set
			{
				if ((this._chiDoan != value))
				{
					this.OnchiDoanChanging(value);
					this.SendPropertyChanging();
					this._chiDoan = value;
					this.SendPropertyChanged("chiDoan");
					this.OnchiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVien", DbType="Bit NOT NULL")]
		public bool doanVien
		{
			get
			{
				return this._doanVien;
			}
			set
			{
				if ((this._doanVien != value))
				{
					this.OndoanVienChanging(value);
					this.SendPropertyChanging();
					this._doanVien = value;
					this.SendPropertyChanged("doanVien");
					this.OndoanVienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaChiDoan")]
	public partial class KetQuaChiDoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _idChiDoan;
		
		private string _idNamHoc;
		
		private string _xepLoai;
		
		private int _xuatSac;
		
		private int _kha;
		
		private int _trungBinh;
		
		private int _yeuKem;
		
		private int _soThanhVien;
		
		private int _tongSV;
		
		private int _tongGV;
		
		private int _tongNuSV;
		
		private int _tongNuGV;
		
		private int _tongDVUT;
		
		private string _ghiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidChiDoanChanging(string value);
    partial void OnidChiDoanChanged();
    partial void OnidNamHocChanging(string value);
    partial void OnidNamHocChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnxuatSacChanging(int value);
    partial void OnxuatSacChanged();
    partial void OnkhaChanging(int value);
    partial void OnkhaChanged();
    partial void OntrungBinhChanging(int value);
    partial void OntrungBinhChanged();
    partial void OnyeuKemChanging(int value);
    partial void OnyeuKemChanged();
    partial void OnsoThanhVienChanging(int value);
    partial void OnsoThanhVienChanged();
    partial void OntongSVChanging(int value);
    partial void OntongSVChanged();
    partial void OntongGVChanging(int value);
    partial void OntongGVChanged();
    partial void OntongNuSVChanging(int value);
    partial void OntongNuSVChanged();
    partial void OntongNuGVChanging(int value);
    partial void OntongNuGVChanged();
    partial void OntongDVUTChanging(int value);
    partial void OntongDVUTChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public KetQuaChiDoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idChiDoan", DbType="VarChar(10)")]
		public string idChiDoan
		{
			get
			{
				return this._idChiDoan;
			}
			set
			{
				if ((this._idChiDoan != value))
				{
					this.OnidChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idChiDoan = value;
					this.SendPropertyChanged("idChiDoan");
					this.OnidChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNamHoc", DbType="VarChar(10)")]
		public string idNamHoc
		{
			get
			{
				return this._idNamHoc;
			}
			set
			{
				if ((this._idNamHoc != value))
				{
					this.OnidNamHocChanging(value);
					this.SendPropertyChanging();
					this._idNamHoc = value;
					this.SendPropertyChanged("idNamHoc");
					this.OnidNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(100)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuatSac", DbType="Int NOT NULL")]
		public int xuatSac
		{
			get
			{
				return this._xuatSac;
			}
			set
			{
				if ((this._xuatSac != value))
				{
					this.OnxuatSacChanging(value);
					this.SendPropertyChanging();
					this._xuatSac = value;
					this.SendPropertyChanged("xuatSac");
					this.OnxuatSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kha", DbType="Int NOT NULL")]
		public int kha
		{
			get
			{
				return this._kha;
			}
			set
			{
				if ((this._kha != value))
				{
					this.OnkhaChanging(value);
					this.SendPropertyChanging();
					this._kha = value;
					this.SendPropertyChanged("kha");
					this.OnkhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trungBinh", DbType="Int NOT NULL")]
		public int trungBinh
		{
			get
			{
				return this._trungBinh;
			}
			set
			{
				if ((this._trungBinh != value))
				{
					this.OntrungBinhChanging(value);
					this.SendPropertyChanging();
					this._trungBinh = value;
					this.SendPropertyChanged("trungBinh");
					this.OntrungBinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeuKem", DbType="Int NOT NULL")]
		public int yeuKem
		{
			get
			{
				return this._yeuKem;
			}
			set
			{
				if ((this._yeuKem != value))
				{
					this.OnyeuKemChanging(value);
					this.SendPropertyChanging();
					this._yeuKem = value;
					this.SendPropertyChanged("yeuKem");
					this.OnyeuKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soThanhVien", DbType="Int NOT NULL")]
		public int soThanhVien
		{
			get
			{
				return this._soThanhVien;
			}
			set
			{
				if ((this._soThanhVien != value))
				{
					this.OnsoThanhVienChanging(value);
					this.SendPropertyChanging();
					this._soThanhVien = value;
					this.SendPropertyChanged("soThanhVien");
					this.OnsoThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSV", DbType="Int NOT NULL")]
		public int tongSV
		{
			get
			{
				return this._tongSV;
			}
			set
			{
				if ((this._tongSV != value))
				{
					this.OntongSVChanging(value);
					this.SendPropertyChanging();
					this._tongSV = value;
					this.SendPropertyChanged("tongSV");
					this.OntongSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongGV", DbType="Int NOT NULL")]
		public int tongGV
		{
			get
			{
				return this._tongGV;
			}
			set
			{
				if ((this._tongGV != value))
				{
					this.OntongGVChanging(value);
					this.SendPropertyChanging();
					this._tongGV = value;
					this.SendPropertyChanged("tongGV");
					this.OntongGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNuSV", DbType="Int NOT NULL")]
		public int tongNuSV
		{
			get
			{
				return this._tongNuSV;
			}
			set
			{
				if ((this._tongNuSV != value))
				{
					this.OntongNuSVChanging(value);
					this.SendPropertyChanging();
					this._tongNuSV = value;
					this.SendPropertyChanged("tongNuSV");
					this.OntongNuSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNuGV", DbType="Int NOT NULL")]
		public int tongNuGV
		{
			get
			{
				return this._tongNuGV;
			}
			set
			{
				if ((this._tongNuGV != value))
				{
					this.OntongNuGVChanging(value);
					this.SendPropertyChanging();
					this._tongNuGV = value;
					this.SendPropertyChanged("tongNuGV");
					this.OntongNuGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongDVUT", DbType="Int NOT NULL")]
		public int tongDVUT
		{
			get
			{
				return this._tongDVUT;
			}
			set
			{
				if ((this._tongDVUT != value))
				{
					this.OntongDVUTChanging(value);
					this.SendPropertyChanging();
					this._tongDVUT = value;
					this.SendPropertyChanged("tongDVUT");
					this.OntongDVUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(1000)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaGiangVien")]
	public partial class KetQuaGiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _idKetQuaChiDoan;
		
		private string _MSGV;
		
		private string _ketQuaDanhGia;
		
		private string _xepLoai;
		
		private string _thanhTichTieuBieu;
		
		private bool _doanVienUuTu;
		
		private string _ghiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidKetQuaChiDoanChanging(System.Nullable<int> value);
    partial void OnidKetQuaChiDoanChanged();
    partial void OnMSGVChanging(string value);
    partial void OnMSGVChanged();
    partial void OnketQuaDanhGiaChanging(string value);
    partial void OnketQuaDanhGiaChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnthanhTichTieuBieuChanging(string value);
    partial void OnthanhTichTieuBieuChanged();
    partial void OndoanVienUuTuChanging(bool value);
    partial void OndoanVienUuTuChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public KetQuaGiangVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKetQuaChiDoan", DbType="Int")]
		public System.Nullable<int> idKetQuaChiDoan
		{
			get
			{
				return this._idKetQuaChiDoan;
			}
			set
			{
				if ((this._idKetQuaChiDoan != value))
				{
					this.OnidKetQuaChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idKetQuaChiDoan = value;
					this.SendPropertyChanged("idKetQuaChiDoan");
					this.OnidKetQuaChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGV", DbType="VarChar(10)")]
		public string MSGV
		{
			get
			{
				return this._MSGV;
			}
			set
			{
				if ((this._MSGV != value))
				{
					this.OnMSGVChanging(value);
					this.SendPropertyChanging();
					this._MSGV = value;
					this.SendPropertyChanged("MSGV");
					this.OnMSGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketQuaDanhGia", DbType="NVarChar(100)")]
		public string ketQuaDanhGia
		{
			get
			{
				return this._ketQuaDanhGia;
			}
			set
			{
				if ((this._ketQuaDanhGia != value))
				{
					this.OnketQuaDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._ketQuaDanhGia = value;
					this.SendPropertyChanged("ketQuaDanhGia");
					this.OnketQuaDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(20)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTichTieuBieu", DbType="NVarChar(200)")]
		public string thanhTichTieuBieu
		{
			get
			{
				return this._thanhTichTieuBieu;
			}
			set
			{
				if ((this._thanhTichTieuBieu != value))
				{
					this.OnthanhTichTieuBieuChanging(value);
					this.SendPropertyChanging();
					this._thanhTichTieuBieu = value;
					this.SendPropertyChanged("thanhTichTieuBieu");
					this.OnthanhTichTieuBieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVienUuTu", DbType="Bit NOT NULL")]
		public bool doanVienUuTu
		{
			get
			{
				return this._doanVienUuTu;
			}
			set
			{
				if ((this._doanVienUuTu != value))
				{
					this.OndoanVienUuTuChanging(value);
					this.SendPropertyChanging();
					this._doanVienUuTu = value;
					this.SendPropertyChanged("doanVienUuTu");
					this.OndoanVienUuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(1000)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaSinhVien")]
	public partial class KetQuaSinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _idKetQuaChiDoan;
		
		private string _MSSV;
		
		private System.Nullable<double> _diemHK1;
		
		private System.Nullable<double> _diemHK2;
		
		private System.Nullable<double> _tongHK;
		
		private System.Nullable<int> _DRLHK1;
		
		private System.Nullable<int> _DRLHK2;
		
		private System.Nullable<int> _DRL;
		
		private string _xepLoai;
		
		private string _thanhTichTieuBieu;
		
		private bool _doanVienUuTu;
		
		private string _ghiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidKetQuaChiDoanChanging(System.Nullable<int> value);
    partial void OnidKetQuaChiDoanChanged();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OndiemHK1Changing(System.Nullable<double> value);
    partial void OndiemHK1Changed();
    partial void OndiemHK2Changing(System.Nullable<double> value);
    partial void OndiemHK2Changed();
    partial void OntongHKChanging(System.Nullable<double> value);
    partial void OntongHKChanged();
    partial void OnDRLHK1Changing(System.Nullable<int> value);
    partial void OnDRLHK1Changed();
    partial void OnDRLHK2Changing(System.Nullable<int> value);
    partial void OnDRLHK2Changed();
    partial void OnDRLChanging(System.Nullable<int> value);
    partial void OnDRLChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnthanhTichTieuBieuChanging(string value);
    partial void OnthanhTichTieuBieuChanged();
    partial void OndoanVienUuTuChanging(bool value);
    partial void OndoanVienUuTuChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public KetQuaSinhVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKetQuaChiDoan", DbType="Int")]
		public System.Nullable<int> idKetQuaChiDoan
		{
			get
			{
				return this._idKetQuaChiDoan;
			}
			set
			{
				if ((this._idKetQuaChiDoan != value))
				{
					this.OnidKetQuaChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idKetQuaChiDoan = value;
					this.SendPropertyChanged("idKetQuaChiDoan");
					this.OnidKetQuaChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(10)")]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemHK1", DbType="Float")]
		public System.Nullable<double> diemHK1
		{
			get
			{
				return this._diemHK1;
			}
			set
			{
				if ((this._diemHK1 != value))
				{
					this.OndiemHK1Changing(value);
					this.SendPropertyChanging();
					this._diemHK1 = value;
					this.SendPropertyChanged("diemHK1");
					this.OndiemHK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemHK2", DbType="Float")]
		public System.Nullable<double> diemHK2
		{
			get
			{
				return this._diemHK2;
			}
			set
			{
				if ((this._diemHK2 != value))
				{
					this.OndiemHK2Changing(value);
					this.SendPropertyChanging();
					this._diemHK2 = value;
					this.SendPropertyChanged("diemHK2");
					this.OndiemHK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongHK", DbType="Float")]
		public System.Nullable<double> tongHK
		{
			get
			{
				return this._tongHK;
			}
			set
			{
				if ((this._tongHK != value))
				{
					this.OntongHKChanging(value);
					this.SendPropertyChanging();
					this._tongHK = value;
					this.SendPropertyChanged("tongHK");
					this.OntongHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRLHK1", DbType="Int")]
		public System.Nullable<int> DRLHK1
		{
			get
			{
				return this._DRLHK1;
			}
			set
			{
				if ((this._DRLHK1 != value))
				{
					this.OnDRLHK1Changing(value);
					this.SendPropertyChanging();
					this._DRLHK1 = value;
					this.SendPropertyChanged("DRLHK1");
					this.OnDRLHK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRLHK2", DbType="Int")]
		public System.Nullable<int> DRLHK2
		{
			get
			{
				return this._DRLHK2;
			}
			set
			{
				if ((this._DRLHK2 != value))
				{
					this.OnDRLHK2Changing(value);
					this.SendPropertyChanging();
					this._DRLHK2 = value;
					this.SendPropertyChanged("DRLHK2");
					this.OnDRLHK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRL", DbType="Int")]
		public System.Nullable<int> DRL
		{
			get
			{
				return this._DRL;
			}
			set
			{
				if ((this._DRL != value))
				{
					this.OnDRLChanging(value);
					this.SendPropertyChanging();
					this._DRL = value;
					this.SendPropertyChanged("DRL");
					this.OnDRLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(100)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTichTieuBieu", DbType="NVarChar(200)")]
		public string thanhTichTieuBieu
		{
			get
			{
				return this._thanhTichTieuBieu;
			}
			set
			{
				if ((this._thanhTichTieuBieu != value))
				{
					this.OnthanhTichTieuBieuChanging(value);
					this.SendPropertyChanging();
					this._thanhTichTieuBieu = value;
					this.SendPropertyChanged("thanhTichTieuBieu");
					this.OnthanhTichTieuBieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVienUuTu", DbType="Bit NOT NULL")]
		public bool doanVienUuTu
		{
			get
			{
				return this._doanVienUuTu;
			}
			set
			{
				if ((this._doanVienUuTu != value))
				{
					this.OndoanVienUuTuChanging(value);
					this.SendPropertyChanging();
					this._doanVienUuTu = value;
					this.SendPropertyChanged("doanVienUuTu");
					this.OndoanVienUuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(1000)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nam")]
	public partial class nam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _ten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    #endregion
		
		public nam()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSSV;
		
		private string _ten;
		
		private string _gioiTinh;
		
		private string _chiDoan;
		
		private bool _doanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnchiDoanChanging(string value);
    partial void OnchiDoanChanged();
    partial void OndoanVienChanging(bool value);
    partial void OndoanVienChanged();
    #endregion
		
		public SinhVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiDoan", DbType="VarChar(10)")]
		public string chiDoan
		{
			get
			{
				return this._chiDoan;
			}
			set
			{
				if ((this._chiDoan != value))
				{
					this.OnchiDoanChanging(value);
					this.SendPropertyChanging();
					this._chiDoan = value;
					this.SendPropertyChanged("chiDoan");
					this.OnchiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVien", DbType="Bit NOT NULL")]
		public bool doanVien
		{
			get
			{
				return this._doanVien;
			}
			set
			{
				if ((this._doanVien != value))
				{
					this.OndoanVienChanging(value);
					this.SendPropertyChanging();
					this._doanVien = value;
					this.SendPropertyChanged("doanVien");
					this.OndoanVienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
