#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanhGiaDoanVien.Other_Class
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="danhGiaDoanVien")]
	public partial class DanhGiaDoanVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertChiDoan(ChiDoan instance);
    partial void UpdateChiDoan(ChiDoan instance);
    partial void DeleteChiDoan(ChiDoan instance);
    partial void InsertDoanVienUuTuGV(DoanVienUuTuGV instance);
    partial void UpdateDoanVienUuTuGV(DoanVienUuTuGV instance);
    partial void DeleteDoanVienUuTuGV(DoanVienUuTuGV instance);
    partial void InsertDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void UpdateDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void DeleteDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertKetQuaChiDoan(KetQuaChiDoan instance);
    partial void UpdateKetQuaChiDoan(KetQuaChiDoan instance);
    partial void DeleteKetQuaChiDoan(KetQuaChiDoan instance);
    partial void InsertKetQuaGiangVien(KetQuaGiangVien instance);
    partial void UpdateKetQuaGiangVien(KetQuaGiangVien instance);
    partial void DeleteKetQuaGiangVien(KetQuaGiangVien instance);
    partial void InsertKetQuaSinhVien(KetQuaSinhVien instance);
    partial void UpdateKetQuaSinhVien(KetQuaSinhVien instance);
    partial void DeleteKetQuaSinhVien(KetQuaSinhVien instance);
    partial void Insertnam(nam instance);
    partial void Updatenam(nam instance);
    partial void Deletenam(nam instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public DanhGiaDoanVienDataContext() : 
				base(global::DanhGiaDoanVien.Properties.Settings.Default.danhGiaDoanVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DanhGiaDoanVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DanhGiaDoanVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DanhGiaDoanVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DanhGiaDoanVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<ChiDoan> ChiDoans
		{
			get
			{
				return this.GetTable<ChiDoan>();
			}
		}
		
		public System.Data.Linq.Table<DoanVienUuTuGV> DoanVienUuTuGVs
		{
			get
			{
				return this.GetTable<DoanVienUuTuGV>();
			}
		}
		
		public System.Data.Linq.Table<DoanVienUuTuSV> DoanVienUuTuSVs
		{
			get
			{
				return this.GetTable<DoanVienUuTuSV>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaChiDoan> KetQuaChiDoans
		{
			get
			{
				return this.GetTable<KetQuaChiDoan>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaGiangVien> KetQuaGiangViens
		{
			get
			{
				return this.GetTable<KetQuaGiangVien>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaSinhVien> KetQuaSinhViens
		{
			get
			{
				return this.GetTable<KetQuaSinhVien>();
			}
		}
		
		public System.Data.Linq.Table<nam> nams
		{
			get
			{
				return this.GetTable<nam>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taiKhoan1;
		
		private string _matKhau;
		
		private string _MSGV;
		
		private EntityRef<GiangVien> _GiangVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaiKhoan1Changing(string value);
    partial void OntaiKhoan1Changed();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnMSGVChanging(string value);
    partial void OnMSGVChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="taiKhoan", Storage="_taiKhoan1", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taiKhoan1
		{
			get
			{
				return this._taiKhoan1;
			}
			set
			{
				if ((this._taiKhoan1 != value))
				{
					this.OntaiKhoan1Changing(value);
					this.SendPropertyChanging();
					this._taiKhoan1 = value;
					this.SendPropertyChanged("taiKhoan1");
					this.OntaiKhoan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGV", DbType="VarChar(10)")]
		public string MSGV
		{
			get
			{
				return this._MSGV;
			}
			set
			{
				if ((this._MSGV != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSGVChanging(value);
					this.SendPropertyChanging();
					this._MSGV = value;
					this.SendPropertyChanged("MSGV");
					this.OnMSGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_TaiKhoan", Storage="_GiangVien", ThisKey="MSGV", OtherKey="MSGV", IsForeignKey=true, DeleteRule="CASCADE")]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MSGV = value.MSGV;
					}
					else
					{
						this._MSGV = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiDoan")]
	public partial class ChiDoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _ten;
		
		private int _soThanhVien;
		
		private int _tongSV;
		
		private int _tongNuSV;
		
		private int _tongGV;
		
		private int _tongNuGV;
		
		private EntitySet<GiangVien> _GiangViens;
		
		private EntitySet<KetQuaChiDoan> _KetQuaChiDoans;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnsoThanhVienChanging(int value);
    partial void OnsoThanhVienChanged();
    partial void OntongSVChanging(int value);
    partial void OntongSVChanged();
    partial void OntongNuSVChanging(int value);
    partial void OntongNuSVChanged();
    partial void OntongGVChanging(int value);
    partial void OntongGVChanged();
    partial void OntongNuGVChanging(int value);
    partial void OntongNuGVChanged();
    #endregion
		
		public ChiDoan()
		{
			this._GiangViens = new EntitySet<GiangVien>(new Action<GiangVien>(this.attach_GiangViens), new Action<GiangVien>(this.detach_GiangViens));
			this._KetQuaChiDoans = new EntitySet<KetQuaChiDoan>(new Action<KetQuaChiDoan>(this.attach_KetQuaChiDoans), new Action<KetQuaChiDoan>(this.detach_KetQuaChiDoans));
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soThanhVien", DbType="Int NOT NULL")]
		public int soThanhVien
		{
			get
			{
				return this._soThanhVien;
			}
			set
			{
				if ((this._soThanhVien != value))
				{
					this.OnsoThanhVienChanging(value);
					this.SendPropertyChanging();
					this._soThanhVien = value;
					this.SendPropertyChanged("soThanhVien");
					this.OnsoThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSV", DbType="Int NOT NULL")]
		public int tongSV
		{
			get
			{
				return this._tongSV;
			}
			set
			{
				if ((this._tongSV != value))
				{
					this.OntongSVChanging(value);
					this.SendPropertyChanging();
					this._tongSV = value;
					this.SendPropertyChanged("tongSV");
					this.OntongSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNuSV", DbType="Int NOT NULL")]
		public int tongNuSV
		{
			get
			{
				return this._tongNuSV;
			}
			set
			{
				if ((this._tongNuSV != value))
				{
					this.OntongNuSVChanging(value);
					this.SendPropertyChanging();
					this._tongNuSV = value;
					this.SendPropertyChanged("tongNuSV");
					this.OntongNuSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongGV", DbType="Int NOT NULL")]
		public int tongGV
		{
			get
			{
				return this._tongGV;
			}
			set
			{
				if ((this._tongGV != value))
				{
					this.OntongGVChanging(value);
					this.SendPropertyChanging();
					this._tongGV = value;
					this.SendPropertyChanged("tongGV");
					this.OntongGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNuGV", DbType="Int NOT NULL")]
		public int tongNuGV
		{
			get
			{
				return this._tongNuGV;
			}
			set
			{
				if ((this._tongNuGV != value))
				{
					this.OntongNuGVChanging(value);
					this.SendPropertyChanging();
					this._tongNuGV = value;
					this.SendPropertyChanged("tongNuGV");
					this.OntongNuGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_GiangVien", Storage="_GiangViens", ThisKey="id", OtherKey="chiDoan")]
		public EntitySet<GiangVien> GiangViens
		{
			get
			{
				return this._GiangViens;
			}
			set
			{
				this._GiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_KetQuaChiDoan", Storage="_KetQuaChiDoans", ThisKey="id", OtherKey="idChiDoan")]
		public EntitySet<KetQuaChiDoan> KetQuaChiDoans
		{
			get
			{
				return this._KetQuaChiDoans;
			}
			set
			{
				this._KetQuaChiDoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_SinhVien", Storage="_SinhViens", ThisKey="id", OtherKey="chiDoan")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan1 = this;
		}
		
		private void detach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan1 = null;
		}
		
		private void attach_KetQuaChiDoans(KetQuaChiDoan entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan = this;
		}
		
		private void detach_KetQuaChiDoans(KetQuaChiDoan entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan = null;
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan1 = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanVienUuTuGV")]
	public partial class DoanVienUuTuGV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _MSGV;
		
		private int _idKetQuaChiDoan;
		
		private int _phieuBau;
		
		private int _tongPhieu;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<KetQuaChiDoan> _KetQuaChiDoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMSGVChanging(string value);
    partial void OnMSGVChanged();
    partial void OnidKetQuaChiDoanChanging(int value);
    partial void OnidKetQuaChiDoanChanged();
    partial void OnphieuBauChanging(int value);
    partial void OnphieuBauChanged();
    partial void OntongPhieuChanging(int value);
    partial void OntongPhieuChanged();
    #endregion
		
		public DoanVienUuTuGV()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			this._KetQuaChiDoan = default(EntityRef<KetQuaChiDoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MSGV
		{
			get
			{
				return this._MSGV;
			}
			set
			{
				if ((this._MSGV != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSGVChanging(value);
					this.SendPropertyChanging();
					this._MSGV = value;
					this.SendPropertyChanged("MSGV");
					this.OnMSGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKetQuaChiDoan", DbType="Int NOT NULL")]
		public int idKetQuaChiDoan
		{
			get
			{
				return this._idKetQuaChiDoan;
			}
			set
			{
				if ((this._idKetQuaChiDoan != value))
				{
					if (this._KetQuaChiDoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKetQuaChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idKetQuaChiDoan = value;
					this.SendPropertyChanged("idKetQuaChiDoan");
					this.OnidKetQuaChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phieuBau", DbType="Int NOT NULL")]
		public int phieuBau
		{
			get
			{
				return this._phieuBau;
			}
			set
			{
				if ((this._phieuBau != value))
				{
					this.OnphieuBauChanging(value);
					this.SendPropertyChanging();
					this._phieuBau = value;
					this.SendPropertyChanged("phieuBau");
					this.OnphieuBauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongPhieu", DbType="Int NOT NULL")]
		public int tongPhieu
		{
			get
			{
				return this._tongPhieu;
			}
			set
			{
				if ((this._tongPhieu != value))
				{
					this.OntongPhieuChanging(value);
					this.SendPropertyChanging();
					this._tongPhieu = value;
					this.SendPropertyChanged("tongPhieu");
					this.OntongPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DoanVienUuTuGV", Storage="_GiangVien", ThisKey="MSGV", OtherKey="MSGV", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.DoanVienUuTuGVs.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.DoanVienUuTuGVs.Add(this);
						this._MSGV = value.MSGV;
					}
					else
					{
						this._MSGV = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQuaChiDoan_DoanVienUuTuGV", Storage="_KetQuaChiDoan", ThisKey="idKetQuaChiDoan", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public KetQuaChiDoan KetQuaChiDoan
		{
			get
			{
				return this._KetQuaChiDoan.Entity;
			}
			set
			{
				KetQuaChiDoan previousValue = this._KetQuaChiDoan.Entity;
				if (((previousValue != value) 
							|| (this._KetQuaChiDoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KetQuaChiDoan.Entity = null;
						previousValue.DoanVienUuTuGVs.Remove(this);
					}
					this._KetQuaChiDoan.Entity = value;
					if ((value != null))
					{
						value.DoanVienUuTuGVs.Add(this);
						this._idKetQuaChiDoan = value.id;
					}
					else
					{
						this._idKetQuaChiDoan = default(int);
					}
					this.SendPropertyChanged("KetQuaChiDoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanVienUuTuSV")]
	public partial class DoanVienUuTuSV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _MSSV;
		
		private int _idKetQuaChiDoan;
		
		private int _phieuBau;
		
		private int _tongPhieu;
		
		private EntityRef<KetQuaChiDoan> _KetQuaChiDoan;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OnidKetQuaChiDoanChanging(int value);
    partial void OnidKetQuaChiDoanChanged();
    partial void OnphieuBauChanging(int value);
    partial void OnphieuBauChanged();
    partial void OntongPhieuChanging(int value);
    partial void OntongPhieuChanged();
    #endregion
		
		public DoanVienUuTuSV()
		{
			this._KetQuaChiDoan = default(EntityRef<KetQuaChiDoan>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKetQuaChiDoan", DbType="Int NOT NULL")]
		public int idKetQuaChiDoan
		{
			get
			{
				return this._idKetQuaChiDoan;
			}
			set
			{
				if ((this._idKetQuaChiDoan != value))
				{
					if (this._KetQuaChiDoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKetQuaChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idKetQuaChiDoan = value;
					this.SendPropertyChanged("idKetQuaChiDoan");
					this.OnidKetQuaChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phieuBau", DbType="Int NOT NULL")]
		public int phieuBau
		{
			get
			{
				return this._phieuBau;
			}
			set
			{
				if ((this._phieuBau != value))
				{
					this.OnphieuBauChanging(value);
					this.SendPropertyChanging();
					this._phieuBau = value;
					this.SendPropertyChanged("phieuBau");
					this.OnphieuBauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongPhieu", DbType="Int NOT NULL")]
		public int tongPhieu
		{
			get
			{
				return this._tongPhieu;
			}
			set
			{
				if ((this._tongPhieu != value))
				{
					this.OntongPhieuChanging(value);
					this.SendPropertyChanging();
					this._tongPhieu = value;
					this.SendPropertyChanged("tongPhieu");
					this.OntongPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQuaChiDoan_DoanVienUuTuSV", Storage="_KetQuaChiDoan", ThisKey="idKetQuaChiDoan", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public KetQuaChiDoan KetQuaChiDoan
		{
			get
			{
				return this._KetQuaChiDoan.Entity;
			}
			set
			{
				KetQuaChiDoan previousValue = this._KetQuaChiDoan.Entity;
				if (((previousValue != value) 
							|| (this._KetQuaChiDoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KetQuaChiDoan.Entity = null;
						previousValue.DoanVienUuTuSVs.Remove(this);
					}
					this._KetQuaChiDoan.Entity = value;
					if ((value != null))
					{
						value.DoanVienUuTuSVs.Add(this);
						this._idKetQuaChiDoan = value.id;
					}
					else
					{
						this._idKetQuaChiDoan = default(int);
					}
					this.SendPropertyChanged("KetQuaChiDoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DoanVienUuTuSV", Storage="_SinhVien", ThisKey="MSSV", OtherKey="MSSV", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.DoanVienUuTuSVs.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.DoanVienUuTuSVs.Add(this);
						this._MSSV = value.MSSV;
					}
					else
					{
						this._MSSV = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSGV;
		
		private string _ten;
		
		private string _gioiTinh;
		
		private string _chiDoan;
		
		private bool _doanVien;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
		private EntitySet<DoanVienUuTuGV> _DoanVienUuTuGVs;
		
		private EntitySet<KetQuaGiangVien> _KetQuaGiangViens;
		
		private EntityRef<ChiDoan> _ChiDoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSGVChanging(string value);
    partial void OnMSGVChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnchiDoanChanging(string value);
    partial void OnchiDoanChanged();
    partial void OndoanVienChanging(bool value);
    partial void OndoanVienChanged();
    #endregion
		
		public GiangVien()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			this._DoanVienUuTuGVs = new EntitySet<DoanVienUuTuGV>(new Action<DoanVienUuTuGV>(this.attach_DoanVienUuTuGVs), new Action<DoanVienUuTuGV>(this.detach_DoanVienUuTuGVs));
			this._KetQuaGiangViens = new EntitySet<KetQuaGiangVien>(new Action<KetQuaGiangVien>(this.attach_KetQuaGiangViens), new Action<KetQuaGiangVien>(this.detach_KetQuaGiangViens));
			this._ChiDoan1 = default(EntityRef<ChiDoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSGV
		{
			get
			{
				return this._MSGV;
			}
			set
			{
				if ((this._MSGV != value))
				{
					this.OnMSGVChanging(value);
					this.SendPropertyChanging();
					this._MSGV = value;
					this.SendPropertyChanged("MSGV");
					this.OnMSGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiDoan", DbType="VarChar(10)")]
		public string chiDoan
		{
			get
			{
				return this._chiDoan;
			}
			set
			{
				if ((this._chiDoan != value))
				{
					if (this._ChiDoan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnchiDoanChanging(value);
					this.SendPropertyChanging();
					this._chiDoan = value;
					this.SendPropertyChanged("chiDoan");
					this.OnchiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVien", DbType="Bit NOT NULL")]
		public bool doanVien
		{
			get
			{
				return this._doanVien;
			}
			set
			{
				if ((this._doanVien != value))
				{
					this.OndoanVienChanging(value);
					this.SendPropertyChanging();
					this._doanVien = value;
					this.SendPropertyChanged("doanVien");
					this.OndoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="MSGV", OtherKey="MSGV")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DoanVienUuTuGV", Storage="_DoanVienUuTuGVs", ThisKey="MSGV", OtherKey="MSGV")]
		public EntitySet<DoanVienUuTuGV> DoanVienUuTuGVs
		{
			get
			{
				return this._DoanVienUuTuGVs;
			}
			set
			{
				this._DoanVienUuTuGVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_KetQuaGiangVien", Storage="_KetQuaGiangViens", ThisKey="MSGV", OtherKey="MSGV")]
		public EntitySet<KetQuaGiangVien> KetQuaGiangViens
		{
			get
			{
				return this._KetQuaGiangViens;
			}
			set
			{
				this._KetQuaGiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_GiangVien", Storage="_ChiDoan1", ThisKey="chiDoan", OtherKey="id", IsForeignKey=true, DeleteRule="SET NULL")]
		public ChiDoan ChiDoan1
		{
			get
			{
				return this._ChiDoan1.Entity;
			}
			set
			{
				ChiDoan previousValue = this._ChiDoan1.Entity;
				if (((previousValue != value) 
							|| (this._ChiDoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiDoan1.Entity = null;
						previousValue.GiangViens.Remove(this);
					}
					this._ChiDoan1.Entity = value;
					if ((value != null))
					{
						value.GiangViens.Add(this);
						this._chiDoan = value.id;
					}
					else
					{
						this._chiDoan = default(string);
					}
					this.SendPropertyChanged("ChiDoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
		
		private void attach_DoanVienUuTuGVs(DoanVienUuTuGV entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_DoanVienUuTuGVs(DoanVienUuTuGV entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
		
		private void attach_KetQuaGiangViens(KetQuaGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_KetQuaGiangViens(KetQuaGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaChiDoan")]
	public partial class KetQuaChiDoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _idChiDoan;
		
		private string _idNamHoc;
		
		private string _xepLoai;
		
		private int _xuatSac;
		
		private int _kha;
		
		private int _trungBinh;
		
		private int _yeuKem;
		
		private int _soThanhVien;
		
		private int _tongSV;
		
		private int _tongGV;
		
		private int _tongNuSV;
		
		private int _tongNuGV;
		
		private int _tongDVUT;
		
		private bool _daXong;
		
		private string _ghiChu;
		
		private EntitySet<DoanVienUuTuGV> _DoanVienUuTuGVs;
		
		private EntitySet<DoanVienUuTuSV> _DoanVienUuTuSVs;
		
		private EntitySet<KetQuaGiangVien> _KetQuaGiangViens;
		
		private EntitySet<KetQuaSinhVien> _KetQuaSinhViens;
		
		private EntityRef<ChiDoan> _ChiDoan;
		
		private EntityRef<nam> _nam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidChiDoanChanging(string value);
    partial void OnidChiDoanChanged();
    partial void OnidNamHocChanging(string value);
    partial void OnidNamHocChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnxuatSacChanging(int value);
    partial void OnxuatSacChanged();
    partial void OnkhaChanging(int value);
    partial void OnkhaChanged();
    partial void OntrungBinhChanging(int value);
    partial void OntrungBinhChanged();
    partial void OnyeuKemChanging(int value);
    partial void OnyeuKemChanged();
    partial void OnsoThanhVienChanging(int value);
    partial void OnsoThanhVienChanged();
    partial void OntongSVChanging(int value);
    partial void OntongSVChanged();
    partial void OntongGVChanging(int value);
    partial void OntongGVChanged();
    partial void OntongNuSVChanging(int value);
    partial void OntongNuSVChanged();
    partial void OntongNuGVChanging(int value);
    partial void OntongNuGVChanged();
    partial void OntongDVUTChanging(int value);
    partial void OntongDVUTChanged();
    partial void OndaXongChanging(bool value);
    partial void OndaXongChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public KetQuaChiDoan()
		{
			this._DoanVienUuTuGVs = new EntitySet<DoanVienUuTuGV>(new Action<DoanVienUuTuGV>(this.attach_DoanVienUuTuGVs), new Action<DoanVienUuTuGV>(this.detach_DoanVienUuTuGVs));
			this._DoanVienUuTuSVs = new EntitySet<DoanVienUuTuSV>(new Action<DoanVienUuTuSV>(this.attach_DoanVienUuTuSVs), new Action<DoanVienUuTuSV>(this.detach_DoanVienUuTuSVs));
			this._KetQuaGiangViens = new EntitySet<KetQuaGiangVien>(new Action<KetQuaGiangVien>(this.attach_KetQuaGiangViens), new Action<KetQuaGiangVien>(this.detach_KetQuaGiangViens));
			this._KetQuaSinhViens = new EntitySet<KetQuaSinhVien>(new Action<KetQuaSinhVien>(this.attach_KetQuaSinhViens), new Action<KetQuaSinhVien>(this.detach_KetQuaSinhViens));
			this._ChiDoan = default(EntityRef<ChiDoan>);
			this._nam = default(EntityRef<nam>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idChiDoan", DbType="VarChar(10)")]
		public string idChiDoan
		{
			get
			{
				return this._idChiDoan;
			}
			set
			{
				if ((this._idChiDoan != value))
				{
					if (this._ChiDoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idChiDoan = value;
					this.SendPropertyChanged("idChiDoan");
					this.OnidChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNamHoc", DbType="VarChar(10)")]
		public string idNamHoc
		{
			get
			{
				return this._idNamHoc;
			}
			set
			{
				if ((this._idNamHoc != value))
				{
					if (this._nam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNamHocChanging(value);
					this.SendPropertyChanging();
					this._idNamHoc = value;
					this.SendPropertyChanged("idNamHoc");
					this.OnidNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(100)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuatSac", DbType="Int NOT NULL")]
		public int xuatSac
		{
			get
			{
				return this._xuatSac;
			}
			set
			{
				if ((this._xuatSac != value))
				{
					this.OnxuatSacChanging(value);
					this.SendPropertyChanging();
					this._xuatSac = value;
					this.SendPropertyChanged("xuatSac");
					this.OnxuatSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kha", DbType="Int NOT NULL")]
		public int kha
		{
			get
			{
				return this._kha;
			}
			set
			{
				if ((this._kha != value))
				{
					this.OnkhaChanging(value);
					this.SendPropertyChanging();
					this._kha = value;
					this.SendPropertyChanged("kha");
					this.OnkhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trungBinh", DbType="Int NOT NULL")]
		public int trungBinh
		{
			get
			{
				return this._trungBinh;
			}
			set
			{
				if ((this._trungBinh != value))
				{
					this.OntrungBinhChanging(value);
					this.SendPropertyChanging();
					this._trungBinh = value;
					this.SendPropertyChanged("trungBinh");
					this.OntrungBinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeuKem", DbType="Int NOT NULL")]
		public int yeuKem
		{
			get
			{
				return this._yeuKem;
			}
			set
			{
				if ((this._yeuKem != value))
				{
					this.OnyeuKemChanging(value);
					this.SendPropertyChanging();
					this._yeuKem = value;
					this.SendPropertyChanged("yeuKem");
					this.OnyeuKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soThanhVien", DbType="Int NOT NULL")]
		public int soThanhVien
		{
			get
			{
				return this._soThanhVien;
			}
			set
			{
				if ((this._soThanhVien != value))
				{
					this.OnsoThanhVienChanging(value);
					this.SendPropertyChanging();
					this._soThanhVien = value;
					this.SendPropertyChanged("soThanhVien");
					this.OnsoThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSV", DbType="Int NOT NULL")]
		public int tongSV
		{
			get
			{
				return this._tongSV;
			}
			set
			{
				if ((this._tongSV != value))
				{
					this.OntongSVChanging(value);
					this.SendPropertyChanging();
					this._tongSV = value;
					this.SendPropertyChanged("tongSV");
					this.OntongSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongGV", DbType="Int NOT NULL")]
		public int tongGV
		{
			get
			{
				return this._tongGV;
			}
			set
			{
				if ((this._tongGV != value))
				{
					this.OntongGVChanging(value);
					this.SendPropertyChanging();
					this._tongGV = value;
					this.SendPropertyChanged("tongGV");
					this.OntongGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNuSV", DbType="Int NOT NULL")]
		public int tongNuSV
		{
			get
			{
				return this._tongNuSV;
			}
			set
			{
				if ((this._tongNuSV != value))
				{
					this.OntongNuSVChanging(value);
					this.SendPropertyChanging();
					this._tongNuSV = value;
					this.SendPropertyChanged("tongNuSV");
					this.OntongNuSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNuGV", DbType="Int NOT NULL")]
		public int tongNuGV
		{
			get
			{
				return this._tongNuGV;
			}
			set
			{
				if ((this._tongNuGV != value))
				{
					this.OntongNuGVChanging(value);
					this.SendPropertyChanging();
					this._tongNuGV = value;
					this.SendPropertyChanged("tongNuGV");
					this.OntongNuGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongDVUT", DbType="Int NOT NULL")]
		public int tongDVUT
		{
			get
			{
				return this._tongDVUT;
			}
			set
			{
				if ((this._tongDVUT != value))
				{
					this.OntongDVUTChanging(value);
					this.SendPropertyChanging();
					this._tongDVUT = value;
					this.SendPropertyChanged("tongDVUT");
					this.OntongDVUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daXong", DbType="Bit NOT NULL")]
		public bool daXong
		{
			get
			{
				return this._daXong;
			}
			set
			{
				if ((this._daXong != value))
				{
					this.OndaXongChanging(value);
					this.SendPropertyChanging();
					this._daXong = value;
					this.SendPropertyChanged("daXong");
					this.OndaXongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(1000)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQuaChiDoan_DoanVienUuTuGV", Storage="_DoanVienUuTuGVs", ThisKey="id", OtherKey="idKetQuaChiDoan")]
		public EntitySet<DoanVienUuTuGV> DoanVienUuTuGVs
		{
			get
			{
				return this._DoanVienUuTuGVs;
			}
			set
			{
				this._DoanVienUuTuGVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQuaChiDoan_DoanVienUuTuSV", Storage="_DoanVienUuTuSVs", ThisKey="id", OtherKey="idKetQuaChiDoan")]
		public EntitySet<DoanVienUuTuSV> DoanVienUuTuSVs
		{
			get
			{
				return this._DoanVienUuTuSVs;
			}
			set
			{
				this._DoanVienUuTuSVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQuaChiDoan_KetQuaGiangVien", Storage="_KetQuaGiangViens", ThisKey="id", OtherKey="idKetQuaChiDoan")]
		public EntitySet<KetQuaGiangVien> KetQuaGiangViens
		{
			get
			{
				return this._KetQuaGiangViens;
			}
			set
			{
				this._KetQuaGiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQuaChiDoan_KetQuaSinhVien", Storage="_KetQuaSinhViens", ThisKey="id", OtherKey="idKetQuaChiDoan")]
		public EntitySet<KetQuaSinhVien> KetQuaSinhViens
		{
			get
			{
				return this._KetQuaSinhViens;
			}
			set
			{
				this._KetQuaSinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_KetQuaChiDoan", Storage="_ChiDoan", ThisKey="idChiDoan", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public ChiDoan ChiDoan
		{
			get
			{
				return this._ChiDoan.Entity;
			}
			set
			{
				ChiDoan previousValue = this._ChiDoan.Entity;
				if (((previousValue != value) 
							|| (this._ChiDoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiDoan.Entity = null;
						previousValue.KetQuaChiDoans.Remove(this);
					}
					this._ChiDoan.Entity = value;
					if ((value != null))
					{
						value.KetQuaChiDoans.Add(this);
						this._idChiDoan = value.id;
					}
					else
					{
						this._idChiDoan = default(string);
					}
					this.SendPropertyChanged("ChiDoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_KetQuaChiDoan", Storage="_nam", ThisKey="idNamHoc", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public nam nam
		{
			get
			{
				return this._nam.Entity;
			}
			set
			{
				nam previousValue = this._nam.Entity;
				if (((previousValue != value) 
							|| (this._nam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nam.Entity = null;
						previousValue.KetQuaChiDoans.Remove(this);
					}
					this._nam.Entity = value;
					if ((value != null))
					{
						value.KetQuaChiDoans.Add(this);
						this._idNamHoc = value.id;
					}
					else
					{
						this._idNamHoc = default(string);
					}
					this.SendPropertyChanged("nam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoanVienUuTuGVs(DoanVienUuTuGV entity)
		{
			this.SendPropertyChanging();
			entity.KetQuaChiDoan = this;
		}
		
		private void detach_DoanVienUuTuGVs(DoanVienUuTuGV entity)
		{
			this.SendPropertyChanging();
			entity.KetQuaChiDoan = null;
		}
		
		private void attach_DoanVienUuTuSVs(DoanVienUuTuSV entity)
		{
			this.SendPropertyChanging();
			entity.KetQuaChiDoan = this;
		}
		
		private void detach_DoanVienUuTuSVs(DoanVienUuTuSV entity)
		{
			this.SendPropertyChanging();
			entity.KetQuaChiDoan = null;
		}
		
		private void attach_KetQuaGiangViens(KetQuaGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.KetQuaChiDoan = this;
		}
		
		private void detach_KetQuaGiangViens(KetQuaGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.KetQuaChiDoan = null;
		}
		
		private void attach_KetQuaSinhViens(KetQuaSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.KetQuaChiDoan = this;
		}
		
		private void detach_KetQuaSinhViens(KetQuaSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.KetQuaChiDoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaGiangVien")]
	public partial class KetQuaGiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _idKetQuaChiDoan;
		
		private string _MSGV;
		
		private string _ketQuaDanhGia;
		
		private string _xepLoai;
		
		private string _thanhTichTieuBieu;
		
		private bool _doanVienUuTu;
		
		private string _ghiChu;
		
		private EntityRef<KetQuaChiDoan> _KetQuaChiDoan;
		
		private EntityRef<GiangVien> _GiangVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidKetQuaChiDoanChanging(System.Nullable<int> value);
    partial void OnidKetQuaChiDoanChanged();
    partial void OnMSGVChanging(string value);
    partial void OnMSGVChanged();
    partial void OnketQuaDanhGiaChanging(string value);
    partial void OnketQuaDanhGiaChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnthanhTichTieuBieuChanging(string value);
    partial void OnthanhTichTieuBieuChanged();
    partial void OndoanVienUuTuChanging(bool value);
    partial void OndoanVienUuTuChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public KetQuaGiangVien()
		{
			this._KetQuaChiDoan = default(EntityRef<KetQuaChiDoan>);
			this._GiangVien = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKetQuaChiDoan", DbType="Int")]
		public System.Nullable<int> idKetQuaChiDoan
		{
			get
			{
				return this._idKetQuaChiDoan;
			}
			set
			{
				if ((this._idKetQuaChiDoan != value))
				{
					if (this._KetQuaChiDoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKetQuaChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idKetQuaChiDoan = value;
					this.SendPropertyChanged("idKetQuaChiDoan");
					this.OnidKetQuaChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGV", DbType="VarChar(10)")]
		public string MSGV
		{
			get
			{
				return this._MSGV;
			}
			set
			{
				if ((this._MSGV != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSGVChanging(value);
					this.SendPropertyChanging();
					this._MSGV = value;
					this.SendPropertyChanged("MSGV");
					this.OnMSGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketQuaDanhGia", DbType="NVarChar(100)")]
		public string ketQuaDanhGia
		{
			get
			{
				return this._ketQuaDanhGia;
			}
			set
			{
				if ((this._ketQuaDanhGia != value))
				{
					this.OnketQuaDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._ketQuaDanhGia = value;
					this.SendPropertyChanged("ketQuaDanhGia");
					this.OnketQuaDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(20)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTichTieuBieu", DbType="NVarChar(200)")]
		public string thanhTichTieuBieu
		{
			get
			{
				return this._thanhTichTieuBieu;
			}
			set
			{
				if ((this._thanhTichTieuBieu != value))
				{
					this.OnthanhTichTieuBieuChanging(value);
					this.SendPropertyChanging();
					this._thanhTichTieuBieu = value;
					this.SendPropertyChanged("thanhTichTieuBieu");
					this.OnthanhTichTieuBieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVienUuTu", DbType="Bit NOT NULL")]
		public bool doanVienUuTu
		{
			get
			{
				return this._doanVienUuTu;
			}
			set
			{
				if ((this._doanVienUuTu != value))
				{
					this.OndoanVienUuTuChanging(value);
					this.SendPropertyChanging();
					this._doanVienUuTu = value;
					this.SendPropertyChanged("doanVienUuTu");
					this.OndoanVienUuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(1000)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQuaChiDoan_KetQuaGiangVien", Storage="_KetQuaChiDoan", ThisKey="idKetQuaChiDoan", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public KetQuaChiDoan KetQuaChiDoan
		{
			get
			{
				return this._KetQuaChiDoan.Entity;
			}
			set
			{
				KetQuaChiDoan previousValue = this._KetQuaChiDoan.Entity;
				if (((previousValue != value) 
							|| (this._KetQuaChiDoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KetQuaChiDoan.Entity = null;
						previousValue.KetQuaGiangViens.Remove(this);
					}
					this._KetQuaChiDoan.Entity = value;
					if ((value != null))
					{
						value.KetQuaGiangViens.Add(this);
						this._idKetQuaChiDoan = value.id;
					}
					else
					{
						this._idKetQuaChiDoan = default(Nullable<int>);
					}
					this.SendPropertyChanged("KetQuaChiDoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_KetQuaGiangVien", Storage="_GiangVien", ThisKey="MSGV", OtherKey="MSGV", IsForeignKey=true, DeleteRule="CASCADE")]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.KetQuaGiangViens.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.KetQuaGiangViens.Add(this);
						this._MSGV = value.MSGV;
					}
					else
					{
						this._MSGV = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaSinhVien")]
	public partial class KetQuaSinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _idKetQuaChiDoan;
		
		private string _MSSV;
		
		private System.Nullable<double> _diemHK1;
		
		private System.Nullable<double> _diemHK2;
		
		private System.Nullable<double> _tongHK;
		
		private System.Nullable<int> _DRLHK1;
		
		private System.Nullable<int> _DRLHK2;
		
		private System.Nullable<int> _DRL;
		
		private string _xepLoai;
		
		private string _thanhTichTieuBieu;
		
		private bool _doanVienUuTu;
		
		private string _ghiChu;
		
		private EntityRef<KetQuaChiDoan> _KetQuaChiDoan;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidKetQuaChiDoanChanging(System.Nullable<int> value);
    partial void OnidKetQuaChiDoanChanged();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OndiemHK1Changing(System.Nullable<double> value);
    partial void OndiemHK1Changed();
    partial void OndiemHK2Changing(System.Nullable<double> value);
    partial void OndiemHK2Changed();
    partial void OntongHKChanging(System.Nullable<double> value);
    partial void OntongHKChanged();
    partial void OnDRLHK1Changing(System.Nullable<int> value);
    partial void OnDRLHK1Changed();
    partial void OnDRLHK2Changing(System.Nullable<int> value);
    partial void OnDRLHK2Changed();
    partial void OnDRLChanging(System.Nullable<int> value);
    partial void OnDRLChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnthanhTichTieuBieuChanging(string value);
    partial void OnthanhTichTieuBieuChanged();
    partial void OndoanVienUuTuChanging(bool value);
    partial void OndoanVienUuTuChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public KetQuaSinhVien()
		{
			this._KetQuaChiDoan = default(EntityRef<KetQuaChiDoan>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKetQuaChiDoan", DbType="Int")]
		public System.Nullable<int> idKetQuaChiDoan
		{
			get
			{
				return this._idKetQuaChiDoan;
			}
			set
			{
				if ((this._idKetQuaChiDoan != value))
				{
					if (this._KetQuaChiDoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKetQuaChiDoanChanging(value);
					this.SendPropertyChanging();
					this._idKetQuaChiDoan = value;
					this.SendPropertyChanged("idKetQuaChiDoan");
					this.OnidKetQuaChiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(10)")]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemHK1", DbType="Float")]
		public System.Nullable<double> diemHK1
		{
			get
			{
				return this._diemHK1;
			}
			set
			{
				if ((this._diemHK1 != value))
				{
					this.OndiemHK1Changing(value);
					this.SendPropertyChanging();
					this._diemHK1 = value;
					this.SendPropertyChanged("diemHK1");
					this.OndiemHK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemHK2", DbType="Float")]
		public System.Nullable<double> diemHK2
		{
			get
			{
				return this._diemHK2;
			}
			set
			{
				if ((this._diemHK2 != value))
				{
					this.OndiemHK2Changing(value);
					this.SendPropertyChanging();
					this._diemHK2 = value;
					this.SendPropertyChanged("diemHK2");
					this.OndiemHK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongHK", DbType="Float")]
		public System.Nullable<double> tongHK
		{
			get
			{
				return this._tongHK;
			}
			set
			{
				if ((this._tongHK != value))
				{
					this.OntongHKChanging(value);
					this.SendPropertyChanging();
					this._tongHK = value;
					this.SendPropertyChanged("tongHK");
					this.OntongHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRLHK1", DbType="Int")]
		public System.Nullable<int> DRLHK1
		{
			get
			{
				return this._DRLHK1;
			}
			set
			{
				if ((this._DRLHK1 != value))
				{
					this.OnDRLHK1Changing(value);
					this.SendPropertyChanging();
					this._DRLHK1 = value;
					this.SendPropertyChanged("DRLHK1");
					this.OnDRLHK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRLHK2", DbType="Int")]
		public System.Nullable<int> DRLHK2
		{
			get
			{
				return this._DRLHK2;
			}
			set
			{
				if ((this._DRLHK2 != value))
				{
					this.OnDRLHK2Changing(value);
					this.SendPropertyChanging();
					this._DRLHK2 = value;
					this.SendPropertyChanged("DRLHK2");
					this.OnDRLHK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRL", DbType="Int")]
		public System.Nullable<int> DRL
		{
			get
			{
				return this._DRL;
			}
			set
			{
				if ((this._DRL != value))
				{
					this.OnDRLChanging(value);
					this.SendPropertyChanging();
					this._DRL = value;
					this.SendPropertyChanged("DRL");
					this.OnDRLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(100)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTichTieuBieu", DbType="NVarChar(200)")]
		public string thanhTichTieuBieu
		{
			get
			{
				return this._thanhTichTieuBieu;
			}
			set
			{
				if ((this._thanhTichTieuBieu != value))
				{
					this.OnthanhTichTieuBieuChanging(value);
					this.SendPropertyChanging();
					this._thanhTichTieuBieu = value;
					this.SendPropertyChanged("thanhTichTieuBieu");
					this.OnthanhTichTieuBieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVienUuTu", DbType="Bit NOT NULL")]
		public bool doanVienUuTu
		{
			get
			{
				return this._doanVienUuTu;
			}
			set
			{
				if ((this._doanVienUuTu != value))
				{
					this.OndoanVienUuTuChanging(value);
					this.SendPropertyChanging();
					this._doanVienUuTu = value;
					this.SendPropertyChanged("doanVienUuTu");
					this.OndoanVienUuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(1000)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQuaChiDoan_KetQuaSinhVien", Storage="_KetQuaChiDoan", ThisKey="idKetQuaChiDoan", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public KetQuaChiDoan KetQuaChiDoan
		{
			get
			{
				return this._KetQuaChiDoan.Entity;
			}
			set
			{
				KetQuaChiDoan previousValue = this._KetQuaChiDoan.Entity;
				if (((previousValue != value) 
							|| (this._KetQuaChiDoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KetQuaChiDoan.Entity = null;
						previousValue.KetQuaSinhViens.Remove(this);
					}
					this._KetQuaChiDoan.Entity = value;
					if ((value != null))
					{
						value.KetQuaSinhViens.Add(this);
						this._idKetQuaChiDoan = value.id;
					}
					else
					{
						this._idKetQuaChiDoan = default(Nullable<int>);
					}
					this.SendPropertyChanged("KetQuaChiDoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_KetQuaSinhVien", Storage="_SinhVien", ThisKey="MSSV", OtherKey="MSSV", IsForeignKey=true, DeleteRule="CASCADE")]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.KetQuaSinhViens.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.KetQuaSinhViens.Add(this);
						this._MSSV = value.MSSV;
					}
					else
					{
						this._MSSV = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nam")]
	public partial class nam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _ten;
		
		private EntitySet<KetQuaChiDoan> _KetQuaChiDoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    #endregion
		
		public nam()
		{
			this._KetQuaChiDoans = new EntitySet<KetQuaChiDoan>(new Action<KetQuaChiDoan>(this.attach_KetQuaChiDoans), new Action<KetQuaChiDoan>(this.detach_KetQuaChiDoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_KetQuaChiDoan", Storage="_KetQuaChiDoans", ThisKey="id", OtherKey="idNamHoc")]
		public EntitySet<KetQuaChiDoan> KetQuaChiDoans
		{
			get
			{
				return this._KetQuaChiDoans;
			}
			set
			{
				this._KetQuaChiDoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KetQuaChiDoans(KetQuaChiDoan entity)
		{
			this.SendPropertyChanging();
			entity.nam = this;
		}
		
		private void detach_KetQuaChiDoans(KetQuaChiDoan entity)
		{
			this.SendPropertyChanging();
			entity.nam = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSSV;
		
		private string _ten;
		
		private string _gioiTinh;
		
		private string _chiDoan;
		
		private bool _doanVien;
		
		private EntitySet<DoanVienUuTuSV> _DoanVienUuTuSVs;
		
		private EntitySet<KetQuaSinhVien> _KetQuaSinhViens;
		
		private EntityRef<ChiDoan> _ChiDoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnchiDoanChanging(string value);
    partial void OnchiDoanChanged();
    partial void OndoanVienChanging(bool value);
    partial void OndoanVienChanged();
    #endregion
		
		public SinhVien()
		{
			this._DoanVienUuTuSVs = new EntitySet<DoanVienUuTuSV>(new Action<DoanVienUuTuSV>(this.attach_DoanVienUuTuSVs), new Action<DoanVienUuTuSV>(this.detach_DoanVienUuTuSVs));
			this._KetQuaSinhViens = new EntitySet<KetQuaSinhVien>(new Action<KetQuaSinhVien>(this.attach_KetQuaSinhViens), new Action<KetQuaSinhVien>(this.detach_KetQuaSinhViens));
			this._ChiDoan1 = default(EntityRef<ChiDoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiDoan", DbType="VarChar(10)")]
		public string chiDoan
		{
			get
			{
				return this._chiDoan;
			}
			set
			{
				if ((this._chiDoan != value))
				{
					if (this._ChiDoan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnchiDoanChanging(value);
					this.SendPropertyChanging();
					this._chiDoan = value;
					this.SendPropertyChanged("chiDoan");
					this.OnchiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVien", DbType="Bit NOT NULL")]
		public bool doanVien
		{
			get
			{
				return this._doanVien;
			}
			set
			{
				if ((this._doanVien != value))
				{
					this.OndoanVienChanging(value);
					this.SendPropertyChanging();
					this._doanVien = value;
					this.SendPropertyChanged("doanVien");
					this.OndoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DoanVienUuTuSV", Storage="_DoanVienUuTuSVs", ThisKey="MSSV", OtherKey="MSSV")]
		public EntitySet<DoanVienUuTuSV> DoanVienUuTuSVs
		{
			get
			{
				return this._DoanVienUuTuSVs;
			}
			set
			{
				this._DoanVienUuTuSVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_KetQuaSinhVien", Storage="_KetQuaSinhViens", ThisKey="MSSV", OtherKey="MSSV")]
		public EntitySet<KetQuaSinhVien> KetQuaSinhViens
		{
			get
			{
				return this._KetQuaSinhViens;
			}
			set
			{
				this._KetQuaSinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_SinhVien", Storage="_ChiDoan1", ThisKey="chiDoan", OtherKey="id", IsForeignKey=true, DeleteRule="SET NULL")]
		public ChiDoan ChiDoan1
		{
			get
			{
				return this._ChiDoan1.Entity;
			}
			set
			{
				ChiDoan previousValue = this._ChiDoan1.Entity;
				if (((previousValue != value) 
							|| (this._ChiDoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiDoan1.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._ChiDoan1.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._chiDoan = value.id;
					}
					else
					{
						this._chiDoan = default(string);
					}
					this.SendPropertyChanged("ChiDoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoanVienUuTuSVs(DoanVienUuTuSV entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_DoanVienUuTuSVs(DoanVienUuTuSV entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
		
		private void attach_KetQuaSinhViens(KetQuaSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_KetQuaSinhViens(KetQuaSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
}
#pragma warning restore 1591
