#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanhGiaDoanVien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="danhGiaDoanVien")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertChiDoan(ChiDoan instance);
    partial void UpdateChiDoan(ChiDoan instance);
    partial void DeleteChiDoan(ChiDoan instance);
    partial void InsertDoanVienUuTuCB(DoanVienUuTuCB instance);
    partial void UpdateDoanVienUuTuCB(DoanVienUuTuCB instance);
    partial void DeleteDoanVienUuTuCB(DoanVienUuTuCB instance);
    partial void InsertDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void UpdateDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void DeleteDoanVienUuTuSV(DoanVienUuTuSV instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertKetQuaChiDoan(KetQuaChiDoan instance);
    partial void UpdateKetQuaChiDoan(KetQuaChiDoan instance);
    partial void DeleteKetQuaChiDoan(KetQuaChiDoan instance);
    partial void InsertKetQuaGiangVien(KetQuaGiangVien instance);
    partial void UpdateKetQuaGiangVien(KetQuaGiangVien instance);
    partial void DeleteKetQuaGiangVien(KetQuaGiangVien instance);
    partial void InsertKetQuaSinhVien(KetQuaSinhVien instance);
    partial void UpdateKetQuaSinhVien(KetQuaSinhVien instance);
    partial void DeleteKetQuaSinhVien(KetQuaSinhVien instance);
    partial void Insertnam(nam instance);
    partial void Updatenam(nam instance);
    partial void Deletenam(nam instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::DanhGiaDoanVien.Properties.Settings.Default.danhGiaDoanVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<ChiDoan> ChiDoans
		{
			get
			{
				return this.GetTable<ChiDoan>();
			}
		}
		
		public System.Data.Linq.Table<DoanVienUuTuCB> DoanVienUuTuCBs
		{
			get
			{
				return this.GetTable<DoanVienUuTuCB>();
			}
		}
		
		public System.Data.Linq.Table<DoanVienUuTuSV> DoanVienUuTuSVs
		{
			get
			{
				return this.GetTable<DoanVienUuTuSV>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaChiDoan> KetQuaChiDoans
		{
			get
			{
				return this.GetTable<KetQuaChiDoan>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaGiangVien> KetQuaGiangViens
		{
			get
			{
				return this.GetTable<KetQuaGiangVien>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaSinhVien> KetQuaSinhViens
		{
			get
			{
				return this.GetTable<KetQuaSinhVien>();
			}
		}
		
		public System.Data.Linq.Table<nam> nams
		{
			get
			{
				return this.GetTable<nam>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taiKhoan1;
		
		private string _matKhau;
		
		private string _MSCB;
		
		private string _loaiTaiKhoan;
		
		private EntityRef<GiangVien> _GiangVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaiKhoan1Changing(string value);
    partial void OntaiKhoan1Changed();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnMSCBChanging(string value);
    partial void OnMSCBChanged();
    partial void OnloaiTaiKhoanChanging(string value);
    partial void OnloaiTaiKhoanChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="taiKhoan", Storage="_taiKhoan1", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taiKhoan1
		{
			get
			{
				return this._taiKhoan1;
			}
			set
			{
				if ((this._taiKhoan1 != value))
				{
					this.OntaiKhoan1Changing(value);
					this.SendPropertyChanging();
					this._taiKhoan1 = value;
					this.SendPropertyChanged("taiKhoan1");
					this.OntaiKhoan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSCB", DbType="VarChar(10)")]
		public string MSCB
		{
			get
			{
				return this._MSCB;
			}
			set
			{
				if ((this._MSCB != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSCBChanging(value);
					this.SendPropertyChanging();
					this._MSCB = value;
					this.SendPropertyChanged("MSCB");
					this.OnMSCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiTaiKhoan", DbType="VarChar(20)")]
		public string loaiTaiKhoan
		{
			get
			{
				return this._loaiTaiKhoan;
			}
			set
			{
				if ((this._loaiTaiKhoan != value))
				{
					this.OnloaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._loaiTaiKhoan = value;
					this.SendPropertyChanged("loaiTaiKhoan");
					this.OnloaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_TaiKhoan", Storage="_GiangVien", ThisKey="MSCB", OtherKey="MSCB", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MSCB = value.MSCB;
					}
					else
					{
						this._MSCB = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiDoan")]
	public partial class ChiDoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _ten;
		
		private byte _soDoanVien;
		
		private byte _tongSV;
		
		private byte _tongGV;
		
		private EntitySet<GiangVien> _GiangViens;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnsoDoanVienChanging(byte value);
    partial void OnsoDoanVienChanged();
    partial void OntongSVChanging(byte value);
    partial void OntongSVChanged();
    partial void OntongGVChanging(byte value);
    partial void OntongGVChanged();
    #endregion
		
		public ChiDoan()
		{
			this._GiangViens = new EntitySet<GiangVien>(new Action<GiangVien>(this.attach_GiangViens), new Action<GiangVien>(this.detach_GiangViens));
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDoanVien", DbType="TinyInt NOT NULL")]
		public byte soDoanVien
		{
			get
			{
				return this._soDoanVien;
			}
			set
			{
				if ((this._soDoanVien != value))
				{
					this.OnsoDoanVienChanging(value);
					this.SendPropertyChanging();
					this._soDoanVien = value;
					this.SendPropertyChanged("soDoanVien");
					this.OnsoDoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSV", DbType="TinyInt NOT NULL")]
		public byte tongSV
		{
			get
			{
				return this._tongSV;
			}
			set
			{
				if ((this._tongSV != value))
				{
					this.OntongSVChanging(value);
					this.SendPropertyChanging();
					this._tongSV = value;
					this.SendPropertyChanged("tongSV");
					this.OntongSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongGV", DbType="TinyInt NOT NULL")]
		public byte tongGV
		{
			get
			{
				return this._tongGV;
			}
			set
			{
				if ((this._tongGV != value))
				{
					this.OntongGVChanging(value);
					this.SendPropertyChanging();
					this._tongGV = value;
					this.SendPropertyChanged("tongGV");
					this.OntongGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_GiangVien", Storage="_GiangViens", ThisKey="id", OtherKey="chiDoan")]
		public EntitySet<GiangVien> GiangViens
		{
			get
			{
				return this._GiangViens;
			}
			set
			{
				this._GiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_SinhVien", Storage="_SinhViens", ThisKey="id", OtherKey="chiDoan")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan1 = this;
		}
		
		private void detach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan1 = null;
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan1 = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiDoan1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanVienUuTuCB")]
	public partial class DoanVienUuTuCB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _MaSo;
		
		private string _idNamHoc;
		
		private byte _phieuBau;
		
		private byte _tongPhieu;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<nam> _nam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMaSoChanging(string value);
    partial void OnMaSoChanged();
    partial void OnidNamHocChanging(string value);
    partial void OnidNamHocChanged();
    partial void OnphieuBauChanging(byte value);
    partial void OnphieuBauChanged();
    partial void OntongPhieuChanging(byte value);
    partial void OntongPhieuChanged();
    #endregion
		
		public DoanVienUuTuCB()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			this._nam = default(EntityRef<nam>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoChanging(value);
					this.SendPropertyChanging();
					this._MaSo = value;
					this.SendPropertyChanged("MaSo");
					this.OnMaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNamHoc", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string idNamHoc
		{
			get
			{
				return this._idNamHoc;
			}
			set
			{
				if ((this._idNamHoc != value))
				{
					if (this._nam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNamHocChanging(value);
					this.SendPropertyChanging();
					this._idNamHoc = value;
					this.SendPropertyChanged("idNamHoc");
					this.OnidNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phieuBau", DbType="TinyInt NOT NULL")]
		public byte phieuBau
		{
			get
			{
				return this._phieuBau;
			}
			set
			{
				if ((this._phieuBau != value))
				{
					this.OnphieuBauChanging(value);
					this.SendPropertyChanging();
					this._phieuBau = value;
					this.SendPropertyChanged("phieuBau");
					this.OnphieuBauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongPhieu", DbType="TinyInt NOT NULL")]
		public byte tongPhieu
		{
			get
			{
				return this._tongPhieu;
			}
			set
			{
				if ((this._tongPhieu != value))
				{
					this.OntongPhieuChanging(value);
					this.SendPropertyChanging();
					this._tongPhieu = value;
					this.SendPropertyChanged("tongPhieu");
					this.OntongPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DoanVienUuTuCB", Storage="_GiangVien", ThisKey="MaSo", OtherKey="MSCB", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.DoanVienUuTuCB = null;
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.DoanVienUuTuCB = this;
						this._MaSo = value.MSCB;
					}
					else
					{
						this._MaSo = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_DoanVienUuTuCB", Storage="_nam", ThisKey="idNamHoc", OtherKey="id", IsForeignKey=true)]
		public nam nam
		{
			get
			{
				return this._nam.Entity;
			}
			set
			{
				nam previousValue = this._nam.Entity;
				if (((previousValue != value) 
							|| (this._nam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nam.Entity = null;
						previousValue.DoanVienUuTuCBs.Remove(this);
					}
					this._nam.Entity = value;
					if ((value != null))
					{
						value.DoanVienUuTuCBs.Add(this);
						this._idNamHoc = value.id;
					}
					else
					{
						this._idNamHoc = default(string);
					}
					this.SendPropertyChanged("nam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanVienUuTuSV")]
	public partial class DoanVienUuTuSV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _MaSo;
		
		private string _idNamHoc;
		
		private byte _phieuBau;
		
		private byte _tongPhieu;
		
		private EntityRef<nam> _nam;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMaSoChanging(string value);
    partial void OnMaSoChanged();
    partial void OnidNamHocChanging(string value);
    partial void OnidNamHocChanged();
    partial void OnphieuBauChanging(byte value);
    partial void OnphieuBauChanged();
    partial void OntongPhieuChanging(byte value);
    partial void OntongPhieuChanged();
    #endregion
		
		public DoanVienUuTuSV()
		{
			this._nam = default(EntityRef<nam>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoChanging(value);
					this.SendPropertyChanging();
					this._MaSo = value;
					this.SendPropertyChanged("MaSo");
					this.OnMaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNamHoc", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string idNamHoc
		{
			get
			{
				return this._idNamHoc;
			}
			set
			{
				if ((this._idNamHoc != value))
				{
					if (this._nam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNamHocChanging(value);
					this.SendPropertyChanging();
					this._idNamHoc = value;
					this.SendPropertyChanged("idNamHoc");
					this.OnidNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phieuBau", DbType="TinyInt NOT NULL")]
		public byte phieuBau
		{
			get
			{
				return this._phieuBau;
			}
			set
			{
				if ((this._phieuBau != value))
				{
					this.OnphieuBauChanging(value);
					this.SendPropertyChanging();
					this._phieuBau = value;
					this.SendPropertyChanged("phieuBau");
					this.OnphieuBauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongPhieu", DbType="TinyInt NOT NULL")]
		public byte tongPhieu
		{
			get
			{
				return this._tongPhieu;
			}
			set
			{
				if ((this._tongPhieu != value))
				{
					this.OntongPhieuChanging(value);
					this.SendPropertyChanging();
					this._tongPhieu = value;
					this.SendPropertyChanged("tongPhieu");
					this.OntongPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_DoanVienUuTuSV", Storage="_nam", ThisKey="idNamHoc", OtherKey="id", IsForeignKey=true)]
		public nam nam
		{
			get
			{
				return this._nam.Entity;
			}
			set
			{
				nam previousValue = this._nam.Entity;
				if (((previousValue != value) 
							|| (this._nam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nam.Entity = null;
						previousValue.DoanVienUuTuSVs.Remove(this);
					}
					this._nam.Entity = value;
					if ((value != null))
					{
						value.DoanVienUuTuSVs.Add(this);
						this._idNamHoc = value.id;
					}
					else
					{
						this._idNamHoc = default(string);
					}
					this.SendPropertyChanged("nam");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DoanVienUuTuSV", Storage="_SinhVien", ThisKey="MaSo", OtherKey="MSSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.DoanVienUuTuSV = null;
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.DoanVienUuTuSV = this;
						this._MaSo = value.MSSV;
					}
					else
					{
						this._MaSo = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSCB;
		
		private string _ten;
		
		private bool _gioiTinh;
		
		private string _chiDoan;
		
		private bool _doanVien;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
		private EntityRef<DoanVienUuTuCB> _DoanVienUuTuCB;
		
		private EntitySet<KetQuaGiangVien> _KetQuaGiangViens;
		
		private EntityRef<ChiDoan> _ChiDoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSCBChanging(string value);
    partial void OnMSCBChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngioiTinhChanging(bool value);
    partial void OngioiTinhChanged();
    partial void OnchiDoanChanging(string value);
    partial void OnchiDoanChanged();
    partial void OndoanVienChanging(bool value);
    partial void OndoanVienChanged();
    #endregion
		
		public GiangVien()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			this._DoanVienUuTuCB = default(EntityRef<DoanVienUuTuCB>);
			this._KetQuaGiangViens = new EntitySet<KetQuaGiangVien>(new Action<KetQuaGiangVien>(this.attach_KetQuaGiangViens), new Action<KetQuaGiangVien>(this.detach_KetQuaGiangViens));
			this._ChiDoan1 = default(EntityRef<ChiDoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSCB", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSCB
		{
			get
			{
				return this._MSCB;
			}
			set
			{
				if ((this._MSCB != value))
				{
					this.OnMSCBChanging(value);
					this.SendPropertyChanging();
					this._MSCB = value;
					this.SendPropertyChanged("MSCB");
					this.OnMSCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit NOT NULL")]
		public bool gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiDoan", DbType="VarChar(10)")]
		public string chiDoan
		{
			get
			{
				return this._chiDoan;
			}
			set
			{
				if ((this._chiDoan != value))
				{
					if (this._ChiDoan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnchiDoanChanging(value);
					this.SendPropertyChanging();
					this._chiDoan = value;
					this.SendPropertyChanged("chiDoan");
					this.OnchiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVien", DbType="Bit NOT NULL")]
		public bool doanVien
		{
			get
			{
				return this._doanVien;
			}
			set
			{
				if ((this._doanVien != value))
				{
					this.OndoanVienChanging(value);
					this.SendPropertyChanging();
					this._doanVien = value;
					this.SendPropertyChanged("doanVien");
					this.OndoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="MSCB", OtherKey="MSCB")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DoanVienUuTuCB", Storage="_DoanVienUuTuCB", ThisKey="MSCB", OtherKey="MaSo", IsUnique=true, IsForeignKey=false)]
		public DoanVienUuTuCB DoanVienUuTuCB
		{
			get
			{
				return this._DoanVienUuTuCB.Entity;
			}
			set
			{
				DoanVienUuTuCB previousValue = this._DoanVienUuTuCB.Entity;
				if (((previousValue != value) 
							|| (this._DoanVienUuTuCB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoanVienUuTuCB.Entity = null;
						previousValue.GiangVien = null;
					}
					this._DoanVienUuTuCB.Entity = value;
					if ((value != null))
					{
						value.GiangVien = this;
					}
					this.SendPropertyChanged("DoanVienUuTuCB");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_KetQuaGiangVien", Storage="_KetQuaGiangViens", ThisKey="MSCB", OtherKey="MSCB")]
		public EntitySet<KetQuaGiangVien> KetQuaGiangViens
		{
			get
			{
				return this._KetQuaGiangViens;
			}
			set
			{
				this._KetQuaGiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_GiangVien", Storage="_ChiDoan1", ThisKey="chiDoan", OtherKey="id", IsForeignKey=true)]
		public ChiDoan ChiDoan1
		{
			get
			{
				return this._ChiDoan1.Entity;
			}
			set
			{
				ChiDoan previousValue = this._ChiDoan1.Entity;
				if (((previousValue != value) 
							|| (this._ChiDoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiDoan1.Entity = null;
						previousValue.GiangViens.Remove(this);
					}
					this._ChiDoan1.Entity = value;
					if ((value != null))
					{
						value.GiangViens.Add(this);
						this._chiDoan = value.id;
					}
					else
					{
						this._chiDoan = default(string);
					}
					this.SendPropertyChanged("ChiDoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
		
		private void attach_KetQuaGiangViens(KetQuaGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_KetQuaGiangViens(KetQuaGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaChiDoan")]
	public partial class KetQuaChiDoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _idNamHoc;
		
		private string _xepLoai;
		
		private System.Nullable<byte> _xuatSac;
		
		private System.Nullable<byte> _kha;
		
		private System.Nullable<byte> _trungBinh;
		
		private System.Nullable<byte> _yeuKem;
		
		private byte _tongDoanVien;
		
		private byte _tongSV;
		
		private byte _tongGV;
		
		private byte _tongDVUT;
		
		private EntityRef<nam> _nam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidNamHocChanging(string value);
    partial void OnidNamHocChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnxuatSacChanging(System.Nullable<byte> value);
    partial void OnxuatSacChanged();
    partial void OnkhaChanging(System.Nullable<byte> value);
    partial void OnkhaChanged();
    partial void OntrungBinhChanging(System.Nullable<byte> value);
    partial void OntrungBinhChanged();
    partial void OnyeuKemChanging(System.Nullable<byte> value);
    partial void OnyeuKemChanged();
    partial void OntongDoanVienChanging(byte value);
    partial void OntongDoanVienChanged();
    partial void OntongSVChanging(byte value);
    partial void OntongSVChanged();
    partial void OntongGVChanging(byte value);
    partial void OntongGVChanged();
    partial void OntongDVUTChanging(byte value);
    partial void OntongDVUTChanged();
    #endregion
		
		public KetQuaChiDoan()
		{
			this._nam = default(EntityRef<nam>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNamHoc", DbType="VarChar(10)")]
		public string idNamHoc
		{
			get
			{
				return this._idNamHoc;
			}
			set
			{
				if ((this._idNamHoc != value))
				{
					if (this._nam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNamHocChanging(value);
					this.SendPropertyChanging();
					this._idNamHoc = value;
					this.SendPropertyChanged("idNamHoc");
					this.OnidNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(100)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuatSac", DbType="TinyInt")]
		public System.Nullable<byte> xuatSac
		{
			get
			{
				return this._xuatSac;
			}
			set
			{
				if ((this._xuatSac != value))
				{
					this.OnxuatSacChanging(value);
					this.SendPropertyChanging();
					this._xuatSac = value;
					this.SendPropertyChanged("xuatSac");
					this.OnxuatSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kha", DbType="TinyInt")]
		public System.Nullable<byte> kha
		{
			get
			{
				return this._kha;
			}
			set
			{
				if ((this._kha != value))
				{
					this.OnkhaChanging(value);
					this.SendPropertyChanging();
					this._kha = value;
					this.SendPropertyChanged("kha");
					this.OnkhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trungBinh", DbType="TinyInt")]
		public System.Nullable<byte> trungBinh
		{
			get
			{
				return this._trungBinh;
			}
			set
			{
				if ((this._trungBinh != value))
				{
					this.OntrungBinhChanging(value);
					this.SendPropertyChanging();
					this._trungBinh = value;
					this.SendPropertyChanged("trungBinh");
					this.OntrungBinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeuKem", DbType="TinyInt")]
		public System.Nullable<byte> yeuKem
		{
			get
			{
				return this._yeuKem;
			}
			set
			{
				if ((this._yeuKem != value))
				{
					this.OnyeuKemChanging(value);
					this.SendPropertyChanging();
					this._yeuKem = value;
					this.SendPropertyChanged("yeuKem");
					this.OnyeuKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongDoanVien", DbType="TinyInt NOT NULL")]
		public byte tongDoanVien
		{
			get
			{
				return this._tongDoanVien;
			}
			set
			{
				if ((this._tongDoanVien != value))
				{
					this.OntongDoanVienChanging(value);
					this.SendPropertyChanging();
					this._tongDoanVien = value;
					this.SendPropertyChanged("tongDoanVien");
					this.OntongDoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSV", DbType="TinyInt NOT NULL")]
		public byte tongSV
		{
			get
			{
				return this._tongSV;
			}
			set
			{
				if ((this._tongSV != value))
				{
					this.OntongSVChanging(value);
					this.SendPropertyChanging();
					this._tongSV = value;
					this.SendPropertyChanged("tongSV");
					this.OntongSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongGV", DbType="TinyInt NOT NULL")]
		public byte tongGV
		{
			get
			{
				return this._tongGV;
			}
			set
			{
				if ((this._tongGV != value))
				{
					this.OntongGVChanging(value);
					this.SendPropertyChanging();
					this._tongGV = value;
					this.SendPropertyChanged("tongGV");
					this.OntongGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongDVUT", DbType="TinyInt NOT NULL")]
		public byte tongDVUT
		{
			get
			{
				return this._tongDVUT;
			}
			set
			{
				if ((this._tongDVUT != value))
				{
					this.OntongDVUTChanging(value);
					this.SendPropertyChanging();
					this._tongDVUT = value;
					this.SendPropertyChanged("tongDVUT");
					this.OntongDVUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_KetQuaChiDoan", Storage="_nam", ThisKey="idNamHoc", OtherKey="id", IsForeignKey=true)]
		public nam nam
		{
			get
			{
				return this._nam.Entity;
			}
			set
			{
				nam previousValue = this._nam.Entity;
				if (((previousValue != value) 
							|| (this._nam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nam.Entity = null;
						previousValue.KetQuaChiDoans.Remove(this);
					}
					this._nam.Entity = value;
					if ((value != null))
					{
						value.KetQuaChiDoans.Add(this);
						this._idNamHoc = value.id;
					}
					else
					{
						this._idNamHoc = default(string);
					}
					this.SendPropertyChanged("nam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaGiangVien")]
	public partial class KetQuaGiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _idNamHoc;
		
		private string _MSCB;
		
		private string _ketQuaDanhGia;
		
		private string _xepLoai;
		
		private string _thanhTichTieuBieu;
		
		private bool _doanVienUuTu;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<nam> _nam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidNamHocChanging(string value);
    partial void OnidNamHocChanged();
    partial void OnMSCBChanging(string value);
    partial void OnMSCBChanged();
    partial void OnketQuaDanhGiaChanging(string value);
    partial void OnketQuaDanhGiaChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnthanhTichTieuBieuChanging(string value);
    partial void OnthanhTichTieuBieuChanged();
    partial void OndoanVienUuTuChanging(bool value);
    partial void OndoanVienUuTuChanged();
    #endregion
		
		public KetQuaGiangVien()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			this._nam = default(EntityRef<nam>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNamHoc", DbType="VarChar(10)")]
		public string idNamHoc
		{
			get
			{
				return this._idNamHoc;
			}
			set
			{
				if ((this._idNamHoc != value))
				{
					if (this._nam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNamHocChanging(value);
					this.SendPropertyChanging();
					this._idNamHoc = value;
					this.SendPropertyChanged("idNamHoc");
					this.OnidNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSCB", DbType="VarChar(10)")]
		public string MSCB
		{
			get
			{
				return this._MSCB;
			}
			set
			{
				if ((this._MSCB != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSCBChanging(value);
					this.SendPropertyChanging();
					this._MSCB = value;
					this.SendPropertyChanged("MSCB");
					this.OnMSCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketQuaDanhGia", DbType="NVarChar(100)")]
		public string ketQuaDanhGia
		{
			get
			{
				return this._ketQuaDanhGia;
			}
			set
			{
				if ((this._ketQuaDanhGia != value))
				{
					this.OnketQuaDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._ketQuaDanhGia = value;
					this.SendPropertyChanged("ketQuaDanhGia");
					this.OnketQuaDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(20)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTichTieuBieu", DbType="NVarChar(200)")]
		public string thanhTichTieuBieu
		{
			get
			{
				return this._thanhTichTieuBieu;
			}
			set
			{
				if ((this._thanhTichTieuBieu != value))
				{
					this.OnthanhTichTieuBieuChanging(value);
					this.SendPropertyChanging();
					this._thanhTichTieuBieu = value;
					this.SendPropertyChanged("thanhTichTieuBieu");
					this.OnthanhTichTieuBieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVienUuTu", DbType="Bit NOT NULL")]
		public bool doanVienUuTu
		{
			get
			{
				return this._doanVienUuTu;
			}
			set
			{
				if ((this._doanVienUuTu != value))
				{
					this.OndoanVienUuTuChanging(value);
					this.SendPropertyChanging();
					this._doanVienUuTu = value;
					this.SendPropertyChanged("doanVienUuTu");
					this.OndoanVienUuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_KetQuaGiangVien", Storage="_GiangVien", ThisKey="MSCB", OtherKey="MSCB", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.KetQuaGiangViens.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.KetQuaGiangViens.Add(this);
						this._MSCB = value.MSCB;
					}
					else
					{
						this._MSCB = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_KetQuaGiangVien", Storage="_nam", ThisKey="idNamHoc", OtherKey="id", IsForeignKey=true)]
		public nam nam
		{
			get
			{
				return this._nam.Entity;
			}
			set
			{
				nam previousValue = this._nam.Entity;
				if (((previousValue != value) 
							|| (this._nam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nam.Entity = null;
						previousValue.KetQuaGiangViens.Remove(this);
					}
					this._nam.Entity = value;
					if ((value != null))
					{
						value.KetQuaGiangViens.Add(this);
						this._idNamHoc = value.id;
					}
					else
					{
						this._idNamHoc = default(string);
					}
					this.SendPropertyChanged("nam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaSinhVien")]
	public partial class KetQuaSinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _idNamHoc;
		
		private string _MSSV;
		
		private System.Nullable<double> _diemHK1;
		
		private System.Nullable<double> _diemHK2;
		
		private System.Nullable<double> _tongHK;
		
		private System.Nullable<byte> _DRLHK1;
		
		private System.Nullable<byte> _DRLHK2;
		
		private System.Nullable<byte> _DRL;
		
		private string _xepLoai;
		
		private string _thanhTichTieuBieu;
		
		private bool _doanVienUuTu;
		
		private EntityRef<nam> _nam;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidNamHocChanging(string value);
    partial void OnidNamHocChanged();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OndiemHK1Changing(System.Nullable<double> value);
    partial void OndiemHK1Changed();
    partial void OndiemHK2Changing(System.Nullable<double> value);
    partial void OndiemHK2Changed();
    partial void OntongHKChanging(System.Nullable<double> value);
    partial void OntongHKChanged();
    partial void OnDRLHK1Changing(System.Nullable<byte> value);
    partial void OnDRLHK1Changed();
    partial void OnDRLHK2Changing(System.Nullable<byte> value);
    partial void OnDRLHK2Changed();
    partial void OnDRLChanging(System.Nullable<byte> value);
    partial void OnDRLChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnthanhTichTieuBieuChanging(string value);
    partial void OnthanhTichTieuBieuChanged();
    partial void OndoanVienUuTuChanging(bool value);
    partial void OndoanVienUuTuChanged();
    #endregion
		
		public KetQuaSinhVien()
		{
			this._nam = default(EntityRef<nam>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNamHoc", DbType="VarChar(10)")]
		public string idNamHoc
		{
			get
			{
				return this._idNamHoc;
			}
			set
			{
				if ((this._idNamHoc != value))
				{
					if (this._nam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNamHocChanging(value);
					this.SendPropertyChanging();
					this._idNamHoc = value;
					this.SendPropertyChanged("idNamHoc");
					this.OnidNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(10)")]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemHK1", DbType="Float")]
		public System.Nullable<double> diemHK1
		{
			get
			{
				return this._diemHK1;
			}
			set
			{
				if ((this._diemHK1 != value))
				{
					this.OndiemHK1Changing(value);
					this.SendPropertyChanging();
					this._diemHK1 = value;
					this.SendPropertyChanged("diemHK1");
					this.OndiemHK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemHK2", DbType="Float")]
		public System.Nullable<double> diemHK2
		{
			get
			{
				return this._diemHK2;
			}
			set
			{
				if ((this._diemHK2 != value))
				{
					this.OndiemHK2Changing(value);
					this.SendPropertyChanging();
					this._diemHK2 = value;
					this.SendPropertyChanged("diemHK2");
					this.OndiemHK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongHK", DbType="Float")]
		public System.Nullable<double> tongHK
		{
			get
			{
				return this._tongHK;
			}
			set
			{
				if ((this._tongHK != value))
				{
					this.OntongHKChanging(value);
					this.SendPropertyChanging();
					this._tongHK = value;
					this.SendPropertyChanged("tongHK");
					this.OntongHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRLHK1", DbType="TinyInt")]
		public System.Nullable<byte> DRLHK1
		{
			get
			{
				return this._DRLHK1;
			}
			set
			{
				if ((this._DRLHK1 != value))
				{
					this.OnDRLHK1Changing(value);
					this.SendPropertyChanging();
					this._DRLHK1 = value;
					this.SendPropertyChanged("DRLHK1");
					this.OnDRLHK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRLHK2", DbType="TinyInt")]
		public System.Nullable<byte> DRLHK2
		{
			get
			{
				return this._DRLHK2;
			}
			set
			{
				if ((this._DRLHK2 != value))
				{
					this.OnDRLHK2Changing(value);
					this.SendPropertyChanging();
					this._DRLHK2 = value;
					this.SendPropertyChanged("DRLHK2");
					this.OnDRLHK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRL", DbType="TinyInt")]
		public System.Nullable<byte> DRL
		{
			get
			{
				return this._DRL;
			}
			set
			{
				if ((this._DRL != value))
				{
					this.OnDRLChanging(value);
					this.SendPropertyChanging();
					this._DRL = value;
					this.SendPropertyChanged("DRL");
					this.OnDRLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(100)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTichTieuBieu", DbType="NVarChar(200)")]
		public string thanhTichTieuBieu
		{
			get
			{
				return this._thanhTichTieuBieu;
			}
			set
			{
				if ((this._thanhTichTieuBieu != value))
				{
					this.OnthanhTichTieuBieuChanging(value);
					this.SendPropertyChanging();
					this._thanhTichTieuBieu = value;
					this.SendPropertyChanged("thanhTichTieuBieu");
					this.OnthanhTichTieuBieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVienUuTu", DbType="Bit NOT NULL")]
		public bool doanVienUuTu
		{
			get
			{
				return this._doanVienUuTu;
			}
			set
			{
				if ((this._doanVienUuTu != value))
				{
					this.OndoanVienUuTuChanging(value);
					this.SendPropertyChanging();
					this._doanVienUuTu = value;
					this.SendPropertyChanged("doanVienUuTu");
					this.OndoanVienUuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_KetQuaSinhVien", Storage="_nam", ThisKey="idNamHoc", OtherKey="id", IsForeignKey=true)]
		public nam nam
		{
			get
			{
				return this._nam.Entity;
			}
			set
			{
				nam previousValue = this._nam.Entity;
				if (((previousValue != value) 
							|| (this._nam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nam.Entity = null;
						previousValue.KetQuaSinhViens.Remove(this);
					}
					this._nam.Entity = value;
					if ((value != null))
					{
						value.KetQuaSinhViens.Add(this);
						this._idNamHoc = value.id;
					}
					else
					{
						this._idNamHoc = default(string);
					}
					this.SendPropertyChanged("nam");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_KetQuaSinhVien", Storage="_SinhVien", ThisKey="MSSV", OtherKey="MSSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.KetQuaSinhViens.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.KetQuaSinhViens.Add(this);
						this._MSSV = value.MSSV;
					}
					else
					{
						this._MSSV = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nam")]
	public partial class nam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _ten;
		
		private EntitySet<DoanVienUuTuCB> _DoanVienUuTuCBs;
		
		private EntitySet<DoanVienUuTuSV> _DoanVienUuTuSVs;
		
		private EntitySet<KetQuaChiDoan> _KetQuaChiDoans;
		
		private EntitySet<KetQuaGiangVien> _KetQuaGiangViens;
		
		private EntitySet<KetQuaSinhVien> _KetQuaSinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    #endregion
		
		public nam()
		{
			this._DoanVienUuTuCBs = new EntitySet<DoanVienUuTuCB>(new Action<DoanVienUuTuCB>(this.attach_DoanVienUuTuCBs), new Action<DoanVienUuTuCB>(this.detach_DoanVienUuTuCBs));
			this._DoanVienUuTuSVs = new EntitySet<DoanVienUuTuSV>(new Action<DoanVienUuTuSV>(this.attach_DoanVienUuTuSVs), new Action<DoanVienUuTuSV>(this.detach_DoanVienUuTuSVs));
			this._KetQuaChiDoans = new EntitySet<KetQuaChiDoan>(new Action<KetQuaChiDoan>(this.attach_KetQuaChiDoans), new Action<KetQuaChiDoan>(this.detach_KetQuaChiDoans));
			this._KetQuaGiangViens = new EntitySet<KetQuaGiangVien>(new Action<KetQuaGiangVien>(this.attach_KetQuaGiangViens), new Action<KetQuaGiangVien>(this.detach_KetQuaGiangViens));
			this._KetQuaSinhViens = new EntitySet<KetQuaSinhVien>(new Action<KetQuaSinhVien>(this.attach_KetQuaSinhViens), new Action<KetQuaSinhVien>(this.detach_KetQuaSinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_DoanVienUuTuCB", Storage="_DoanVienUuTuCBs", ThisKey="id", OtherKey="idNamHoc")]
		public EntitySet<DoanVienUuTuCB> DoanVienUuTuCBs
		{
			get
			{
				return this._DoanVienUuTuCBs;
			}
			set
			{
				this._DoanVienUuTuCBs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_DoanVienUuTuSV", Storage="_DoanVienUuTuSVs", ThisKey="id", OtherKey="idNamHoc")]
		public EntitySet<DoanVienUuTuSV> DoanVienUuTuSVs
		{
			get
			{
				return this._DoanVienUuTuSVs;
			}
			set
			{
				this._DoanVienUuTuSVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_KetQuaChiDoan", Storage="_KetQuaChiDoans", ThisKey="id", OtherKey="idNamHoc")]
		public EntitySet<KetQuaChiDoan> KetQuaChiDoans
		{
			get
			{
				return this._KetQuaChiDoans;
			}
			set
			{
				this._KetQuaChiDoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_KetQuaGiangVien", Storage="_KetQuaGiangViens", ThisKey="id", OtherKey="idNamHoc")]
		public EntitySet<KetQuaGiangVien> KetQuaGiangViens
		{
			get
			{
				return this._KetQuaGiangViens;
			}
			set
			{
				this._KetQuaGiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nam_KetQuaSinhVien", Storage="_KetQuaSinhViens", ThisKey="id", OtherKey="idNamHoc")]
		public EntitySet<KetQuaSinhVien> KetQuaSinhViens
		{
			get
			{
				return this._KetQuaSinhViens;
			}
			set
			{
				this._KetQuaSinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoanVienUuTuCBs(DoanVienUuTuCB entity)
		{
			this.SendPropertyChanging();
			entity.nam = this;
		}
		
		private void detach_DoanVienUuTuCBs(DoanVienUuTuCB entity)
		{
			this.SendPropertyChanging();
			entity.nam = null;
		}
		
		private void attach_DoanVienUuTuSVs(DoanVienUuTuSV entity)
		{
			this.SendPropertyChanging();
			entity.nam = this;
		}
		
		private void detach_DoanVienUuTuSVs(DoanVienUuTuSV entity)
		{
			this.SendPropertyChanging();
			entity.nam = null;
		}
		
		private void attach_KetQuaChiDoans(KetQuaChiDoan entity)
		{
			this.SendPropertyChanging();
			entity.nam = this;
		}
		
		private void detach_KetQuaChiDoans(KetQuaChiDoan entity)
		{
			this.SendPropertyChanging();
			entity.nam = null;
		}
		
		private void attach_KetQuaGiangViens(KetQuaGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.nam = this;
		}
		
		private void detach_KetQuaGiangViens(KetQuaGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.nam = null;
		}
		
		private void attach_KetQuaSinhViens(KetQuaSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.nam = this;
		}
		
		private void detach_KetQuaSinhViens(KetQuaSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.nam = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSSV;
		
		private string _ten;
		
		private string _lop;
		
		private bool _gioiTinh;
		
		private string _chiDoan;
		
		private bool _doanVien;
		
		private EntityRef<DoanVienUuTuSV> _DoanVienUuTuSV;
		
		private EntitySet<KetQuaSinhVien> _KetQuaSinhViens;
		
		private EntityRef<ChiDoan> _ChiDoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnlopChanging(string value);
    partial void OnlopChanged();
    partial void OngioiTinhChanging(bool value);
    partial void OngioiTinhChanged();
    partial void OnchiDoanChanging(string value);
    partial void OnchiDoanChanged();
    partial void OndoanVienChanging(bool value);
    partial void OndoanVienChanged();
    #endregion
		
		public SinhVien()
		{
			this._DoanVienUuTuSV = default(EntityRef<DoanVienUuTuSV>);
			this._KetQuaSinhViens = new EntitySet<KetQuaSinhVien>(new Action<KetQuaSinhVien>(this.attach_KetQuaSinhViens), new Action<KetQuaSinhVien>(this.detach_KetQuaSinhViens));
			this._ChiDoan1 = default(EntityRef<ChiDoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NVarChar(100)")]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this.OnlopChanging(value);
					this.SendPropertyChanging();
					this._lop = value;
					this.SendPropertyChanged("lop");
					this.OnlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit NOT NULL")]
		public bool gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiDoan", DbType="VarChar(10)")]
		public string chiDoan
		{
			get
			{
				return this._chiDoan;
			}
			set
			{
				if ((this._chiDoan != value))
				{
					if (this._ChiDoan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnchiDoanChanging(value);
					this.SendPropertyChanging();
					this._chiDoan = value;
					this.SendPropertyChanged("chiDoan");
					this.OnchiDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanVien", DbType="Bit NOT NULL")]
		public bool doanVien
		{
			get
			{
				return this._doanVien;
			}
			set
			{
				if ((this._doanVien != value))
				{
					this.OndoanVienChanging(value);
					this.SendPropertyChanging();
					this._doanVien = value;
					this.SendPropertyChanged("doanVien");
					this.OndoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DoanVienUuTuSV", Storage="_DoanVienUuTuSV", ThisKey="MSSV", OtherKey="MaSo", IsUnique=true, IsForeignKey=false)]
		public DoanVienUuTuSV DoanVienUuTuSV
		{
			get
			{
				return this._DoanVienUuTuSV.Entity;
			}
			set
			{
				DoanVienUuTuSV previousValue = this._DoanVienUuTuSV.Entity;
				if (((previousValue != value) 
							|| (this._DoanVienUuTuSV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoanVienUuTuSV.Entity = null;
						previousValue.SinhVien = null;
					}
					this._DoanVienUuTuSV.Entity = value;
					if ((value != null))
					{
						value.SinhVien = this;
					}
					this.SendPropertyChanged("DoanVienUuTuSV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_KetQuaSinhVien", Storage="_KetQuaSinhViens", ThisKey="MSSV", OtherKey="MSSV")]
		public EntitySet<KetQuaSinhVien> KetQuaSinhViens
		{
			get
			{
				return this._KetQuaSinhViens;
			}
			set
			{
				this._KetQuaSinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiDoan_SinhVien", Storage="_ChiDoan1", ThisKey="chiDoan", OtherKey="id", IsForeignKey=true)]
		public ChiDoan ChiDoan1
		{
			get
			{
				return this._ChiDoan1.Entity;
			}
			set
			{
				ChiDoan previousValue = this._ChiDoan1.Entity;
				if (((previousValue != value) 
							|| (this._ChiDoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiDoan1.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._ChiDoan1.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._chiDoan = value.id;
					}
					else
					{
						this._chiDoan = default(string);
					}
					this.SendPropertyChanged("ChiDoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KetQuaSinhViens(KetQuaSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_KetQuaSinhViens(KetQuaSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
}
#pragma warning restore 1591
